#!/bin/sh
# Run an old-binary chain under cosmovisor through a governance upgrade to the registered new plan.
# Configuration, environment variables, and scratch outputs are documented in README.md.
set -eu

ROOT=$(cd "$(dirname "$0")/../.." && pwd)
cd "$ROOT"

WORK=${WORK:-$ROOT/build/upgrade-rehearsal}
# The old binary is the last release when there is one: that is the binary
# validators run, and a rehearsal from HEAD would only ever migrate state HEAD
# itself wrote. Before the first release there is nothing but HEAD.
OLD_REF=${OLD_REF:-$(git describe --tags --abbrev=0 --match 'v[0-9]*' 2>/dev/null || echo HEAD)}
UPGRADE_DELAY=${UPGRADE_DELAY:-50}
COSMOVISOR_VERSION=${COSMOVISOR_VERSION:-v1.7.3}
CHAIN_ID=ark-rehearsal
RPC=http://localhost:26657
API=http://localhost:1317

if [ -z "${UPGRADE_NAME:-}" ]; then
  UPGRADE_NAME=$(ls -d app/upgrade/v* 2>/dev/null | sed 's|.*/||' | sort -V | tail -1)
  if [ -z "$UPGRADE_NAME" ]; then
    echo "no app/upgrade/v* package to rehearse; set UPGRADE_NAME to a plan the new binary registers" >&2
    exit 2
  fi
fi

# The node binds the default ports, so a Docker localnet or any other node on
# this host would silently answer the queries below in its place.
if curl -sf "$RPC/status" >/dev/null 2>&1; then
  echo "another node is already serving $RPC; stop it (make localnet-stop) before rehearsing" >&2
  exit 2
fi

rm -rf "$WORK"
mkdir -p "$WORK/bin"

cleanup() {
  if [ -n "${NODE_PID:-}" ]; then
    kill "$NODE_PID" 2>/dev/null || true
    wait "$NODE_PID" 2>/dev/null || true
  fi
  git worktree remove --force "$WORK/old-src" 2>/dev/null || true
}
trap cleanup EXIT INT TERM

# build_arkd <output>: builds ./cmd/arkd from the current directory with the
# version stamps `make build` applies, so the probe can show which binary
# is serving.
build_arkd() {
  go build -trimpath -o "$1" \
    -ldflags "-X github.com/cosmos/cosmos-sdk/version.Version=$(git describe --tags --match 'v[0-9]*' --always --dirty) \
      -X github.com/cosmos/cosmos-sdk/version.Commit=$(git rev-parse HEAD)" \
    ./cmd/arkd
}

if [ -z "${OLD_BINARY:-}" ]; then
  echo "building old arkd from $OLD_REF"
  git worktree add --detach "$WORK/old-src" "$OLD_REF" >/dev/null
  (cd "$WORK/old-src" && build_arkd "$WORK/bin/arkd-old")
  git worktree remove --force "$WORK/old-src"
  OLD_BINARY=$WORK/bin/arkd-old
fi

if [ -z "${NEW_BINARY:-}" ]; then
  echo "building new arkd from the working tree"
  build_arkd "$WORK/bin/arkd-new"
  NEW_BINARY=$WORK/bin/arkd-new
fi

if ! command -v cosmovisor >/dev/null 2>&1; then
  echo "installing cosmovisor $COSMOVISOR_VERSION into $WORK/bin"
  GOBIN="$WORK/bin" go install "cosmossdk.io/tools/cosmovisor/cmd/cosmovisor@$COSMOVISOR_VERSION"
  PATH="$WORK/bin:$PATH"
fi

# One validator, generated by the old binary so the state the upgrade
# migrates is state the old release wrote. It starts from the testnet
# artefact when the old binary can, so the rehearsal migrates launch-shaped
# state; an old release without --genesis generates from its defaults.
export COSMOS_SDK_CONFIG_SCOPE=arkd
GENESIS=${GENESIS:-$ROOT/app/genesis/testnet.json}
GENESIS_FLAG=""
if "$OLD_BINARY" testnet init-files --help 2>/dev/null | grep -q -- '--genesis'; then
  GENESIS_FLAG="--genesis $GENESIS"
else
  echo "old binary has no --genesis flag; generating from its defaults"
fi
"$OLD_BINARY" testnet init-files $GENESIS_FLAG \
  --validator-count 1 \
  --output-dir "$WORK/testnet" \
  --chain-id "$CHAIN_ID" \
  --keyring-backend test \
  --node-daemon-home arkd \
  --commit-timeout 1s
HOME_DIR=$WORK/testnet/node0/arkd
GENESIS=$HOME_DIR/config/genesis.json

# Use short voting, enabled vote extensions, and noop telemetry for the sidecar-free rehearsal.
# Supply a NOAH fee factor for any input genesis lacking one; the chain cannot derive it without
# live reference prices.
jq '.app_state.gov.params.voting_period = "20s"
  | .app_state.gov.params.expedited_voting_period = "10s"
  | .consensus.params.abci.vote_extensions_enable_height = "1"
  | .app_state.treasury.conversion_factors = [{"denom": "anoah", "factor": "1.000000000000000000", "derived_height": "0"}]' \
  "$GENESIS" > "$GENESIS.tmp"
mv "$GENESIS.tmp" "$GENESIS"
: > "$HOME_DIR/config/otel.yaml"


DEPOSIT=$(jq -r '.app_state.gov.params.min_deposit[0] | .amount + .denom' "$GENESIS")
# Twice the Treasury floor per gas, in NOAH at the unit factor: comfortably
# above the base fee on an idle chain and far below the validator's balance.
GAS_PRICE=$(jq -r '.app_state.treasury.params.min_base_gas_price | tonumber * 2 | floor' "$GENESIS")
FEE_FLAGS=""
if [ "$GAS_PRICE" -gt 0 ]; then
  FEE_FLAGS="--gas-prices ${GAS_PRICE}anoah"
fi

export DAEMON_NAME=arkd
export DAEMON_HOME=$HOME_DIR
export DAEMON_ALLOW_DOWNLOAD_BINARIES=false
export DAEMON_RESTART_AFTER_UPGRADE=true
export UNSAFE_SKIP_BACKUP=true
cosmovisor init "$OLD_BINARY" > "$WORK/cosmovisor-init.log" 2>&1
cosmovisor add-upgrade "$UPGRADE_NAME" "$NEW_BINARY" >> "$WORK/cosmovisor-init.log" 2>&1

cosmovisor run start --home "$HOME_DIR" > "$WORK/node.log" 2>&1 &
NODE_PID=$!

height() { curl -sf "$RPC/status" | jq -r '.result.sync_info.latest_block_height // empty' 2>/dev/null; }
# q <args...>: queries through the rehearsal home, so no client.toml elsewhere redirects it.
q() { "$OLD_BINARY" q "$@" --home "$HOME_DIR" --output json; }

# wait_for <seconds> <command...>: polls once a second until the command succeeds.
wait_for() {
  n=$1
  shift
  while [ "$n" -gt 0 ]; do
    if "$@" >/dev/null 2>&1; then return 0; fi
    n=$((n - 1))
    sleep 1
  done
  return 1
}
chain_started() { h=$(height); [ -n "$h" ] && [ "$h" -ge 2 ]; }

echo "waiting for the chain under cosmovisor"
wait_for 90 chain_started || { echo "chain did not start; see $WORK/node.log" >&2; exit 1; }

# tx <args...>: signs with the validator key, broadcasts, waits for inclusion,
# and fails on a non-zero code either at CheckTx or in the block. A fixed gas
# limit keeps the rehearsal independent of gas estimation.
tx() {
  # shellcheck disable=SC2086 # FEE_FLAGS is intentionally word-split
  out=$("$OLD_BINARY" tx "$@" \
    --from node0 --keyring-backend test --home "$HOME_DIR" --chain-id "$CHAIN_ID" \
    --gas 400000 $FEE_FLAGS \
    --broadcast-mode sync --output json --yes)
  if [ "$(echo "$out" | jq -r .code)" != "0" ]; then
    echo "$out" >&2
    return 1
  fi
  hash=$(echo "$out" | jq -r .txhash)
  tx_included() { q tx "$hash"; }
  wait_for 30 tx_included || { echo "tx $hash was not included" >&2; return 1; }
  result=$(q tx "$hash")
  if [ "$(echo "$result" | jq -r .code)" != "0" ]; then
    echo "$result" | jq -r .raw_log >&2
    return 1
  fi
}

UPGRADE_HEIGHT=$(( $(height) + UPGRADE_DELAY ))
echo "proposing $UPGRADE_NAME at height $UPGRADE_HEIGHT with deposit $DEPOSIT"
tx upgrade software-upgrade "$UPGRADE_NAME" \
  --upgrade-height "$UPGRADE_HEIGHT" --upgrade-info rehearsal --no-validate \
  --title "rehearse $UPGRADE_NAME" --summary "upgrade rehearsal" --deposit "$DEPOSIT"
PROPOSAL=$(q gov proposals | jq -r '.proposals[-1].id')
echo "voting yes on proposal $PROPOSAL"
tx gov vote "$PROPOSAL" yes

proposal_status() { q gov proposal "$PROPOSAL" | jq -r '.proposal.status'; }
while :; do
  status=$(proposal_status)
  case "$status" in
    PROPOSAL_STATUS_PASSED) break ;;
    PROPOSAL_STATUS_VOTING_PERIOD | PROPOSAL_STATUS_DEPOSIT_PERIOD) ;;
    *) echo "proposal $PROPOSAL ended as $status" >&2; exit 1 ;;
  esac
  h=$(height)
  if [ -n "$h" ] && [ "$h" -ge "$UPGRADE_HEIGHT" ]; then
    echo "upgrade height $UPGRADE_HEIGHT reached while proposal is still $status; raise UPGRADE_DELAY" >&2
    exit 1
  fi
  sleep 2
done
echo "proposal $PROPOSAL passed at height $(height); waiting for the halt and switch"

contrib/scripts/upgrade-probe.sh 120 2 "$UPGRADE_HEIGHT" "$UPGRADE_NAME" "$RPC" "$API"
