// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: ark/treasury/v1/event.proto

package types

import (
	cosmossdk_io_math "cosmossdk.io/math"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// EventTaxCapsUpdated is emitted after the complete derived tax-cap set
// changes.
type EventTaxCapsUpdated struct {
	TaxCaps []TaxCap `protobuf:"bytes,1,rep,name=tax_caps,json=taxCaps,proto3" json:"tax_caps"`
}

func (m *EventTaxCapsUpdated) Reset()         { *m = EventTaxCapsUpdated{} }
func (m *EventTaxCapsUpdated) String() string { return proto.CompactTextString(m) }
func (*EventTaxCapsUpdated) ProtoMessage()    {}
func (*EventTaxCapsUpdated) Descriptor() ([]byte, []int) {
	return fileDescriptor_f861eec5413b282d, []int{0}
}
func (m *EventTaxCapsUpdated) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EventTaxCapsUpdated) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EventTaxCapsUpdated.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EventTaxCapsUpdated) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventTaxCapsUpdated.Merge(m, src)
}
func (m *EventTaxCapsUpdated) XXX_Size() int {
	return m.Size()
}
func (m *EventTaxCapsUpdated) XXX_DiscardUnknown() {
	xxx_messageInfo_EventTaxCapsUpdated.DiscardUnknown(m)
}

var xxx_messageInfo_EventTaxCapsUpdated proto.InternalMessageInfo

func (m *EventTaxCapsUpdated) GetTaxCaps() []TaxCap {
	if m != nil {
		return m.TaxCaps
	}
	return nil
}

// EventBlockRewardsToppedUp is emitted after a reward-funding window settles.
type EventBlockRewardsToppedUp struct {
	Denom            string                `protobuf:"bytes,1,opt,name=denom,proto3" json:"denom,omitempty"`
	ValidatorTarget  cosmossdk_io_math.Int `protobuf:"bytes,2,opt,name=validator_target,json=validatorTarget,proto3,customtype=cosmossdk.io/math.Int" json:"validator_target"`
	OracleTarget     cosmossdk_io_math.Int `protobuf:"bytes,3,opt,name=oracle_target,json=oracleTarget,proto3,customtype=cosmossdk.io/math.Int" json:"oracle_target"`
	ValidatorOrganic cosmossdk_io_math.Int `protobuf:"bytes,4,opt,name=validator_organic,json=validatorOrganic,proto3,customtype=cosmossdk.io/math.Int" json:"validator_organic"`
	OracleOrganic    cosmossdk_io_math.Int `protobuf:"bytes,5,opt,name=oracle_organic,json=oracleOrganic,proto3,customtype=cosmossdk.io/math.Int" json:"oracle_organic"`
	ValidatorPaid    cosmossdk_io_math.Int `protobuf:"bytes,6,opt,name=validator_paid,json=validatorPaid,proto3,customtype=cosmossdk.io/math.Int" json:"validator_paid"`
	OraclePaid       cosmossdk_io_math.Int `protobuf:"bytes,7,opt,name=oracle_paid,json=oraclePaid,proto3,customtype=cosmossdk.io/math.Int" json:"oracle_paid"`
}

func (m *EventBlockRewardsToppedUp) Reset()         { *m = EventBlockRewardsToppedUp{} }
func (m *EventBlockRewardsToppedUp) String() string { return proto.CompactTextString(m) }
func (*EventBlockRewardsToppedUp) ProtoMessage()    {}
func (*EventBlockRewardsToppedUp) Descriptor() ([]byte, []int) {
	return fileDescriptor_f861eec5413b282d, []int{1}
}
func (m *EventBlockRewardsToppedUp) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EventBlockRewardsToppedUp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EventBlockRewardsToppedUp.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EventBlockRewardsToppedUp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventBlockRewardsToppedUp.Merge(m, src)
}
func (m *EventBlockRewardsToppedUp) XXX_Size() int {
	return m.Size()
}
func (m *EventBlockRewardsToppedUp) XXX_DiscardUnknown() {
	xxx_messageInfo_EventBlockRewardsToppedUp.DiscardUnknown(m)
}

var xxx_messageInfo_EventBlockRewardsToppedUp proto.InternalMessageInfo

func (m *EventBlockRewardsToppedUp) GetDenom() string {
	if m != nil {
		return m.Denom
	}
	return ""
}

// EventUnpricedStabilityTaxRouted reports settlement routing of stability tax
// held in denominations without a usable Oracle rate. Moved supply belongs to
// written-off or retired assets and now sits in the strategic reserve;
// deferred supply stays in the collector awaiting a returning feed.
type EventUnpricedStabilityTaxRouted struct {
	Moved    github_com_cosmos_cosmos_sdk_types.Coins `protobuf:"bytes,1,rep,name=moved,proto3,castrepeated=github.com/cosmos/cosmos-sdk/types.Coins" json:"moved"`
	Deferred github_com_cosmos_cosmos_sdk_types.Coins `protobuf:"bytes,2,rep,name=deferred,proto3,castrepeated=github.com/cosmos/cosmos-sdk/types.Coins" json:"deferred"`
}

func (m *EventUnpricedStabilityTaxRouted) Reset()         { *m = EventUnpricedStabilityTaxRouted{} }
func (m *EventUnpricedStabilityTaxRouted) String() string { return proto.CompactTextString(m) }
func (*EventUnpricedStabilityTaxRouted) ProtoMessage()    {}
func (*EventUnpricedStabilityTaxRouted) Descriptor() ([]byte, []int) {
	return fileDescriptor_f861eec5413b282d, []int{2}
}
func (m *EventUnpricedStabilityTaxRouted) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EventUnpricedStabilityTaxRouted) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EventUnpricedStabilityTaxRouted.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EventUnpricedStabilityTaxRouted) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventUnpricedStabilityTaxRouted.Merge(m, src)
}
func (m *EventUnpricedStabilityTaxRouted) XXX_Size() int {
	return m.Size()
}
func (m *EventUnpricedStabilityTaxRouted) XXX_DiscardUnknown() {
	xxx_messageInfo_EventUnpricedStabilityTaxRouted.DiscardUnknown(m)
}

var xxx_messageInfo_EventUnpricedStabilityTaxRouted proto.InternalMessageInfo

func (m *EventUnpricedStabilityTaxRouted) GetMoved() github_com_cosmos_cosmos_sdk_types.Coins {
	if m != nil {
		return m.Moved
	}
	return nil
}

func (m *EventUnpricedStabilityTaxRouted) GetDeferred() github_com_cosmos_cosmos_sdk_types.Coins {
	if m != nil {
		return m.Deferred
	}
	return nil
}

// EventLiabilityIncomplete discloses a block whose liability valuation could
// not cover every recognized liability, and is emitted only in that degraded
// state. At least one of the two supply lists below is non-empty and is the
// reason. No fund target is sized while it fires.
type EventLiabilityIncomplete struct {
	// claimable_liability is the aggregate that can currently redeem, in anoah.
	// It is still the denominator redemption coverage divides by; what it no
	// longer supports is sizing a fund target.
	ClaimableLiability types.DecCoin `protobuf:"bytes,1,opt,name=claimable_liability,json=claimableLiability,proto3" json:"claimable_liability"`
	// stale_member_supply is supply whose feed was unavailable. It is still
	// counted above at its last known rate: an absent feed is absent evidence,
	// not an extinguished obligation.
	StaleMemberSupply []types.Coin `protobuf:"bytes,2,rep,name=stale_member_supply,json=staleMemberSupply,proto3" json:"stale_member_supply"`
	// untrusted_suspended_supply is SUSPENDED supply with no settlement plan,
	// valuable by no honest rate and so outside the aggregate entirely.
	UntrustedSuspendedSupply []types.Coin `protobuf:"bytes,3,rep,name=untrusted_suspended_supply,json=untrustedSuspendedSupply,proto3" json:"untrusted_suspended_supply"`
}

func (m *EventLiabilityIncomplete) Reset()         { *m = EventLiabilityIncomplete{} }
func (m *EventLiabilityIncomplete) String() string { return proto.CompactTextString(m) }
func (*EventLiabilityIncomplete) ProtoMessage()    {}
func (*EventLiabilityIncomplete) Descriptor() ([]byte, []int) {
	return fileDescriptor_f861eec5413b282d, []int{3}
}
func (m *EventLiabilityIncomplete) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EventLiabilityIncomplete) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EventLiabilityIncomplete.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EventLiabilityIncomplete) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventLiabilityIncomplete.Merge(m, src)
}
func (m *EventLiabilityIncomplete) XXX_Size() int {
	return m.Size()
}
func (m *EventLiabilityIncomplete) XXX_DiscardUnknown() {
	xxx_messageInfo_EventLiabilityIncomplete.DiscardUnknown(m)
}

var xxx_messageInfo_EventLiabilityIncomplete proto.InternalMessageInfo

func (m *EventLiabilityIncomplete) GetClaimableLiability() types.DecCoin {
	if m != nil {
		return m.ClaimableLiability
	}
	return types.DecCoin{}
}

func (m *EventLiabilityIncomplete) GetStaleMemberSupply() []types.Coin {
	if m != nil {
		return m.StaleMemberSupply
	}
	return nil
}

func (m *EventLiabilityIncomplete) GetUntrustedSuspendedSupply() []types.Coin {
	if m != nil {
		return m.UntrustedSuspendedSupply
	}
	return nil
}

// EventExpansionAllocated records the complete realised expansion allocation.
type EventExpansionAllocated struct {
	Denom                  string                `protobuf:"bytes,1,opt,name=denom,proto3" json:"denom,omitempty"`
	RedemptionBufferCredit cosmossdk_io_math.Int `protobuf:"bytes,2,opt,name=redemption_buffer_credit,json=redemptionBufferCredit,proto3,customtype=cosmossdk.io/math.Int" json:"redemption_buffer_credit"`
	StrategicReserveCredit cosmossdk_io_math.Int `protobuf:"bytes,3,opt,name=strategic_reserve_credit,json=strategicReserveCredit,proto3,customtype=cosmossdk.io/math.Int" json:"strategic_reserve_credit"`
	InsuranceCredit        cosmossdk_io_math.Int `protobuf:"bytes,4,opt,name=insurance_credit,json=insuranceCredit,proto3,customtype=cosmossdk.io/math.Int" json:"insurance_credit"`
	SpreadAndDustBurn      cosmossdk_io_math.Int `protobuf:"bytes,5,opt,name=spread_and_dust_burn,json=spreadAndDustBurn,proto3,customtype=cosmossdk.io/math.Int" json:"spread_and_dust_burn"`
	OverflowBurn           cosmossdk_io_math.Int `protobuf:"bytes,6,opt,name=overflow_burn,json=overflowBurn,proto3,customtype=cosmossdk.io/math.Int" json:"overflow_burn"`
}

func (m *EventExpansionAllocated) Reset()         { *m = EventExpansionAllocated{} }
func (m *EventExpansionAllocated) String() string { return proto.CompactTextString(m) }
func (*EventExpansionAllocated) ProtoMessage()    {}
func (*EventExpansionAllocated) Descriptor() ([]byte, []int) {
	return fileDescriptor_f861eec5413b282d, []int{4}
}
func (m *EventExpansionAllocated) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EventExpansionAllocated) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EventExpansionAllocated.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EventExpansionAllocated) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventExpansionAllocated.Merge(m, src)
}
func (m *EventExpansionAllocated) XXX_Size() int {
	return m.Size()
}
func (m *EventExpansionAllocated) XXX_DiscardUnknown() {
	xxx_messageInfo_EventExpansionAllocated.DiscardUnknown(m)
}

var xxx_messageInfo_EventExpansionAllocated proto.InternalMessageInfo

func (m *EventExpansionAllocated) GetDenom() string {
	if m != nil {
		return m.Denom
	}
	return ""
}

// EventRedemptionBufferDrawn records a successful redemption-buffer payment.
type EventRedemptionBufferDrawn struct {
	Denom   string                `protobuf:"bytes,1,opt,name=denom,proto3" json:"denom,omitempty"`
	Payment cosmossdk_io_math.Int `protobuf:"bytes,2,opt,name=payment,proto3,customtype=cosmossdk.io/math.Int" json:"payment"`
}

func (m *EventRedemptionBufferDrawn) Reset()         { *m = EventRedemptionBufferDrawn{} }
func (m *EventRedemptionBufferDrawn) String() string { return proto.CompactTextString(m) }
func (*EventRedemptionBufferDrawn) ProtoMessage()    {}
func (*EventRedemptionBufferDrawn) Descriptor() ([]byte, []int) {
	return fileDescriptor_f861eec5413b282d, []int{5}
}
func (m *EventRedemptionBufferDrawn) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EventRedemptionBufferDrawn) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EventRedemptionBufferDrawn.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EventRedemptionBufferDrawn) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventRedemptionBufferDrawn.Merge(m, src)
}
func (m *EventRedemptionBufferDrawn) XXX_Size() int {
	return m.Size()
}
func (m *EventRedemptionBufferDrawn) XXX_DiscardUnknown() {
	xxx_messageInfo_EventRedemptionBufferDrawn.DiscardUnknown(m)
}

var xxx_messageInfo_EventRedemptionBufferDrawn proto.InternalMessageInfo

func (m *EventRedemptionBufferDrawn) GetDenom() string {
	if m != nil {
		return m.Denom
	}
	return ""
}

// EventMonetaryMandateSet is emitted when governance appoints, replaces, or
// disables the monetary-policy committee. A disabling carries the empty
// committee and the advanced term.
type EventMonetaryMandateSet struct {
	Term uint64 `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	// committee is empty when governance disabled the mandate.
	Committee        string `protobuf:"bytes,2,opt,name=committee,proto3" json:"committee,omitempty"`
	ActivationHeight uint64 `protobuf:"varint,3,opt,name=activation_height,json=activationHeight,proto3" json:"activation_height,omitempty"`
	ExpiryHeight     uint64 `protobuf:"varint,4,opt,name=expiry_height,json=expiryHeight,proto3" json:"expiry_height,omitempty"`
}

func (m *EventMonetaryMandateSet) Reset()         { *m = EventMonetaryMandateSet{} }
func (m *EventMonetaryMandateSet) String() string { return proto.CompactTextString(m) }
func (*EventMonetaryMandateSet) ProtoMessage()    {}
func (*EventMonetaryMandateSet) Descriptor() ([]byte, []int) {
	return fileDescriptor_f861eec5413b282d, []int{6}
}
func (m *EventMonetaryMandateSet) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EventMonetaryMandateSet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EventMonetaryMandateSet.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EventMonetaryMandateSet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventMonetaryMandateSet.Merge(m, src)
}
func (m *EventMonetaryMandateSet) XXX_Size() int {
	return m.Size()
}
func (m *EventMonetaryMandateSet) XXX_DiscardUnknown() {
	xxx_messageInfo_EventMonetaryMandateSet.DiscardUnknown(m)
}

var xxx_messageInfo_EventMonetaryMandateSet proto.InternalMessageInfo

func (m *EventMonetaryMandateSet) GetTerm() uint64 {
	if m != nil {
		return m.Term
	}
	return 0
}

func (m *EventMonetaryMandateSet) GetCommittee() string {
	if m != nil {
		return m.Committee
	}
	return ""
}

func (m *EventMonetaryMandateSet) GetActivationHeight() uint64 {
	if m != nil {
		return m.ActivationHeight
	}
	return 0
}

func (m *EventMonetaryMandateSet) GetExpiryHeight() uint64 {
	if m != nil {
		return m.ExpiryHeight
	}
	return 0
}

// EventReferenceTaxCapRebased records the reference tax cap re-expressed in a
// new protocol reference unit. Emitted only by RebaseTaxCap, whose only caller
// is MsgSetReference.
type EventReferenceTaxCapRebased struct {
	OldCap types.Coin `protobuf:"bytes,1,opt,name=old_cap,json=oldCap,proto3" json:"old_cap"`
	NewCap types.Coin `protobuf:"bytes,2,opt,name=new_cap,json=newCap,proto3" json:"new_cap"`
}

func (m *EventReferenceTaxCapRebased) Reset()         { *m = EventReferenceTaxCapRebased{} }
func (m *EventReferenceTaxCapRebased) String() string { return proto.CompactTextString(m) }
func (*EventReferenceTaxCapRebased) ProtoMessage()    {}
func (*EventReferenceTaxCapRebased) Descriptor() ([]byte, []int) {
	return fileDescriptor_f861eec5413b282d, []int{7}
}
func (m *EventReferenceTaxCapRebased) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EventReferenceTaxCapRebased) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EventReferenceTaxCapRebased.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EventReferenceTaxCapRebased) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventReferenceTaxCapRebased.Merge(m, src)
}
func (m *EventReferenceTaxCapRebased) XXX_Size() int {
	return m.Size()
}
func (m *EventReferenceTaxCapRebased) XXX_DiscardUnknown() {
	xxx_messageInfo_EventReferenceTaxCapRebased.DiscardUnknown(m)
}

var xxx_messageInfo_EventReferenceTaxCapRebased proto.InternalMessageInfo

func (m *EventReferenceTaxCapRebased) GetOldCap() types.Coin {
	if m != nil {
		return m.OldCap
	}
	return types.Coin{}
}

func (m *EventReferenceTaxCapRebased) GetNewCap() types.Coin {
	if m != nil {
		return m.NewCap
	}
	return types.Coin{}
}

func init() {
	proto.RegisterType((*EventTaxCapsUpdated)(nil), "ark.treasury.v1.EventTaxCapsUpdated")
	proto.RegisterType((*EventBlockRewardsToppedUp)(nil), "ark.treasury.v1.EventBlockRewardsToppedUp")
	proto.RegisterType((*EventUnpricedStabilityTaxRouted)(nil), "ark.treasury.v1.EventUnpricedStabilityTaxRouted")
	proto.RegisterType((*EventLiabilityIncomplete)(nil), "ark.treasury.v1.EventLiabilityIncomplete")
	proto.RegisterType((*EventExpansionAllocated)(nil), "ark.treasury.v1.EventExpansionAllocated")
	proto.RegisterType((*EventRedemptionBufferDrawn)(nil), "ark.treasury.v1.EventRedemptionBufferDrawn")
	proto.RegisterType((*EventMonetaryMandateSet)(nil), "ark.treasury.v1.EventMonetaryMandateSet")
	proto.RegisterType((*EventReferenceTaxCapRebased)(nil), "ark.treasury.v1.EventReferenceTaxCapRebased")
}

func init() { proto.RegisterFile("ark/treasury/v1/event.proto", fileDescriptor_f861eec5413b282d) }

var fileDescriptor_f861eec5413b282d = []byte{
	// 987 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x96, 0xcf, 0x4f, 0x24, 0x45,
	0x14, 0xc7, 0x19, 0x76, 0x80, 0xa5, 0x60, 0x05, 0x1a, 0xdc, 0x6d, 0x58, 0x33, 0x6c, 0xe6, 0x44,
	0x48, 0xe8, 0x16, 0x8c, 0xde, 0x3c, 0x30, 0xb0, 0x89, 0x18, 0x89, 0x3a, 0x40, 0x34, 0x6e, 0x4c,
	0xa7, 0xa6, 0xea, 0xcd, 0x50, 0xd2, 0x5d, 0x55, 0xa9, 0xaa, 0x9e, 0x1f, 0x17, 0xff, 0x06, 0xcf,
	0x9a, 0x78, 0x36, 0x9e, 0xf6, 0xb0, 0x7f, 0xc4, 0x9a, 0x78, 0x20, 0x7b, 0x32, 0x1e, 0x56, 0x03,
	0x87, 0xfd, 0x13, 0xbc, 0x9a, 0xae, 0xaa, 0xe9, 0x21, 0x64, 0xd5, 0xd8, 0xc6, 0xcb, 0x4c, 0x77,
	0xbf, 0x57, 0x9f, 0xef, 0x7b, 0x3d, 0xef, 0xbd, 0x79, 0xe8, 0x21, 0x56, 0x17, 0xb1, 0x51, 0x80,
	0x75, 0xae, 0x46, 0x71, 0x7f, 0x37, 0x86, 0x3e, 0x70, 0x13, 0x49, 0x25, 0x8c, 0x08, 0x96, 0xb0,
	0xba, 0x88, 0xc6, 0xc6, 0xa8, 0xbf, 0xbb, 0xb1, 0x82, 0x33, 0xc6, 0x45, 0x6c, 0x3f, 0x9d, 0xcf,
	0x46, 0xe3, 0x36, 0xa0, 0xf4, 0xf7, 0x76, 0x22, 0x74, 0x26, 0x74, 0xdc, 0xc1, 0x1a, 0xe2, 0xfe,
	0x6e, 0x07, 0x0c, 0xde, 0x8d, 0x89, 0x60, 0xdc, 0xdb, 0xd7, 0x9d, 0x3d, 0xb1, 0x77, 0xb1, 0xbb,
	0xf1, 0xa6, 0xb5, 0x9e, 0xe8, 0x09, 0xf7, 0xbc, 0xb8, 0x72, 0x4f, 0x9b, 0xa7, 0x68, 0xf5, 0x71,
	0x11, 0xe3, 0x29, 0x1e, 0x1e, 0x60, 0xa9, 0xcf, 0x24, 0xc5, 0x06, 0x68, 0xf0, 0x3e, 0xba, 0x6b,
	0xf0, 0x30, 0x21, 0x58, 0xea, 0xb0, 0xf6, 0xe8, 0xce, 0xd6, 0xc2, 0xde, 0x83, 0xe8, 0x56, 0xf8,
	0x91, 0x3b, 0xd2, 0x9a, 0x7f, 0xfe, 0x72, 0x73, 0xea, 0x87, 0x57, 0x4f, 0xb7, 0x6b, 0xed, 0x39,
	0xe3, 0x28, 0xcd, 0x9f, 0xea, 0x68, 0xdd, 0x62, 0x5b, 0xa9, 0x20, 0x17, 0x6d, 0x18, 0x60, 0x45,
	0xf5, 0xa9, 0x90, 0x12, 0xe8, 0x99, 0x0c, 0xd6, 0xd0, 0x0c, 0x05, 0x2e, 0xb2, 0xb0, 0xf6, 0xa8,
	0xb6, 0x35, 0xdf, 0x76, 0x37, 0xc1, 0x13, 0xb4, 0xdc, 0xc7, 0x29, 0xa3, 0xd8, 0x08, 0x95, 0x18,
	0xac, 0x7a, 0x60, 0xc2, 0xe9, 0xc2, 0xa1, 0xf5, 0x76, 0xa1, 0xf0, 0xeb, 0xcb, 0xcd, 0x37, 0x5d,
	0x3e, 0x9a, 0x5e, 0x44, 0x4c, 0xc4, 0x19, 0x36, 0xe7, 0xd1, 0x11, 0x37, 0x2f, 0x9e, 0xed, 0x20,
	0x9f, 0xe8, 0x11, 0x37, 0x2e, 0x90, 0xa5, 0x92, 0x74, 0x6a, 0x41, 0xc1, 0x19, 0xba, 0x27, 0x14,
	0x26, 0x29, 0x8c, 0xc9, 0x77, 0x2a, 0x92, 0x17, 0x1d, 0xc6, 0x63, 0xbf, 0x44, 0x2b, 0x93, 0x98,
	0x85, 0xea, 0x61, 0xce, 0x48, 0x58, 0xaf, 0x88, 0x9e, 0xa4, 0xff, 0xb1, 0x23, 0x05, 0x9f, 0xa1,
	0x37, 0x7c, 0xd4, 0x63, 0xf6, 0x4c, 0x45, 0xb6, 0xcf, 0xfe, 0x06, 0x78, 0x12, 0xb7, 0xc4, 0x8c,
	0x86, 0xb3, 0x55, 0xc1, 0x25, 0xe7, 0x13, 0xcc, 0x68, 0xf0, 0x29, 0x5a, 0xf0, 0x11, 0x5b, 0xea,
	0x5c, 0x45, 0x2a, 0x72, 0x90, 0x02, 0xd9, 0xfc, 0xa3, 0x86, 0x36, 0x6d, 0x2d, 0x9d, 0x71, 0xa9,
	0x18, 0x01, 0x7a, 0x62, 0x70, 0x87, 0xa5, 0xcc, 0x8c, 0x4e, 0xf1, 0xb0, 0x2d, 0xf2, 0xa2, 0x5c,
	0xbb, 0x68, 0x26, 0x13, 0x7d, 0xa0, 0xbe, 0x56, 0xd7, 0x23, 0x0f, 0x2c, 0xda, 0x24, 0xf2, 0x6d,
	0x12, 0x1d, 0x08, 0xc6, 0x5b, 0xef, 0x16, 0xb1, 0xfc, 0xf8, 0xdb, 0xe6, 0x56, 0x8f, 0x99, 0xf3,
	0xbc, 0x13, 0x11, 0x91, 0xf9, 0x36, 0xf1, 0x5f, 0x3b, 0x9a, 0x5e, 0xc4, 0x66, 0x24, 0x41, 0xdb,
	0x03, 0xda, 0x05, 0xe4, 0xf0, 0x41, 0x8a, 0xee, 0x52, 0xe8, 0x82, 0x52, 0x40, 0xc3, 0xe9, 0xff,
	0x49, 0xaa, 0x54, 0x68, 0x5e, 0x4e, 0xa3, 0xd0, 0x66, 0xfe, 0x11, 0xf3, 0x19, 0x1f, 0x71, 0x22,
	0x32, 0x99, 0x82, 0x81, 0xe0, 0x73, 0xb4, 0x4a, 0x52, 0xcc, 0x32, 0xdc, 0x49, 0x21, 0x49, 0xc7,
	0x0e, 0xb6, 0xa5, 0x16, 0xf6, 0xde, 0x7a, 0x6d, 0x54, 0x87, 0x40, 0x6c, 0x60, 0x37, 0x3a, 0x36,
	0x28, 0x19, 0xa5, 0x46, 0x00, 0x68, 0x55, 0x1b, 0x9c, 0x42, 0x92, 0x41, 0xd6, 0x01, 0x95, 0xe8,
	0x5c, 0xca, 0x74, 0xf4, 0xcf, 0xf9, 0x6e, 0x14, 0xd8, 0x6f, 0x5f, 0x3d, 0xdd, 0x5e, 0x4c, 0xa1,
	0x87, 0xc9, 0x28, 0x21, 0x93, 0xa4, 0x56, 0x2c, 0xf1, 0xd8, 0x02, 0x4f, 0x2c, 0x2f, 0xd0, 0x68,
	0x23, 0xe7, 0x46, 0xe5, 0xda, 0x00, 0x4d, 0x74, 0xae, 0x25, 0x70, 0x6a, 0xaf, 0xac, 0xda, 0x9d,
	0xff, 0xa2, 0x16, 0x96, 0xe0, 0x93, 0x31, 0xd7, 0x89, 0x36, 0xbf, 0xaf, 0xa3, 0x07, 0xf6, 0x95,
	0x3e, 0x1e, 0x4a, 0xcc, 0x35, 0x13, 0x7c, 0x3f, 0x4d, 0x05, 0xb1, 0x33, 0xef, 0xf5, 0x63, 0xe9,
	0x2b, 0x14, 0x2a, 0xa0, 0x90, 0x49, 0xc3, 0x04, 0x4f, 0x3a, 0x79, 0xb7, 0x0b, 0x2a, 0x21, 0x0a,
	0x28, 0xab, 0x3e, 0x9e, 0xee, 0x4f, 0x88, 0x2d, 0x0b, 0x3c, 0xb0, 0xbc, 0x42, 0x4b, 0x1b, 0x85,
	0x0d, 0xf4, 0x18, 0x49, 0x14, 0x68, 0x50, 0x7d, 0x18, 0x6b, 0x55, 0x1d, 0x58, 0xf7, 0x4b, 0x62,
	0xdb, 0x01, 0xbd, 0xd6, 0x13, 0xb4, 0xcc, 0xb8, 0xce, 0x15, 0xe6, 0xa4, 0xd4, 0xa8, 0x3a, 0xb9,
	0x96, 0x4a, 0x92, 0x87, 0x63, 0xb4, 0xa6, 0xa5, 0x02, 0x4c, 0x13, 0xcc, 0x69, 0x42, 0x73, 0x6d,
	0x92, 0x4e, 0xae, 0x78, 0xe5, 0xf1, 0xb5, 0xe2, 0x68, 0xfb, 0x9c, 0x1e, 0xe6, 0xda, 0xb4, 0x72,
	0xc5, 0xed, 0x44, 0xef, 0x83, 0xea, 0xa6, 0x62, 0xe0, 0xd8, 0xb3, 0x95, 0x27, 0xba, 0xc7, 0x14,
	0xd8, 0xe6, 0xd7, 0x68, 0xc3, 0xd6, 0x47, 0xfb, 0xd6, 0x2f, 0x74, 0xa8, 0xf0, 0x80, 0xff, 0x45,
	0x89, 0x7c, 0x88, 0xe6, 0x24, 0x1e, 0x65, 0xc0, 0xab, 0x57, 0xc4, 0x18, 0xd0, 0xfc, 0xb9, 0xe6,
	0x0b, 0xf4, 0x58, 0x70, 0x30, 0x58, 0x8d, 0x8e, 0x31, 0x2f, 0xfe, 0x92, 0x4f, 0xc0, 0x04, 0xeb,
	0xa8, 0x6e, 0x40, 0x39, 0xf1, 0x7a, 0x6b, 0xc6, 0x9d, 0xb4, 0x8f, 0x82, 0xf7, 0xd0, 0x3c, 0x11,
	0x59, 0xc6, 0x8c, 0x01, 0xf0, 0x41, 0x84, 0x2f, 0x9e, 0xed, 0xac, 0x79, 0x9d, 0x7d, 0x4a, 0x15,
	0x68, 0x7d, 0x62, 0x14, 0xe3, 0xbd, 0xf6, 0xc4, 0x35, 0xd8, 0x43, 0x2b, 0x98, 0x18, 0xd6, 0xc7,
	0xb6, 0xba, 0xcf, 0x81, 0xf5, 0xce, 0x5d, 0xa9, 0x95, 0xfc, 0xe5, 0x89, 0xfd, 0x03, 0x6b, 0x0e,
	0xb6, 0xd1, 0x3d, 0x18, 0x4a, 0xa6, 0x46, 0x63, 0xff, 0xfa, 0x4d, 0xff, 0x45, 0x67, 0x73, 0xbe,
	0xcd, 0xef, 0x6a, 0xe8, 0xa1, 0x7f, 0x9f, 0x5d, 0x50, 0xc0, 0x09, 0xb8, 0xad, 0xa1, 0x0d, 0x45,
	0x47, 0x17, 0x7b, 0xc6, 0x9c, 0x48, 0x69, 0xb1, 0x67, 0xf8, 0xc9, 0xf5, 0x37, 0x1d, 0x7f, 0x63,
	0x6c, 0xcd, 0x8a, 0x94, 0x1e, 0x60, 0x59, 0x1c, 0xe7, 0x30, 0xb0, 0xc7, 0xa7, 0xff, 0xcd, 0x71,
	0x0e, 0x83, 0x62, 0x75, 0x89, 0x9e, 0x5f, 0x35, 0x6a, 0x97, 0x57, 0x8d, 0xda, 0xef, 0x57, 0x8d,
	0xda, 0x37, 0xd7, 0x8d, 0xa9, 0xcb, 0xeb, 0xc6, 0xd4, 0x2f, 0xd7, 0x8d, 0xa9, 0x2f, 0xd6, 0x8a,
	0x3d, 0x6c, 0x38, 0xd9, 0xc4, 0xec, 0x94, 0xee, 0xcc, 0xda, 0x9d, 0xe9, 0x9d, 0x3f, 0x03, 0x00,
	0x00, 0xff, 0xff, 0x9b, 0x34, 0x4f, 0x4e, 0xe7, 0x09, 0x00, 0x00,
}

func (m *EventTaxCapsUpdated) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EventTaxCapsUpdated) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EventTaxCapsUpdated) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.TaxCaps) > 0 {
		for iNdEx := len(m.TaxCaps) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.TaxCaps[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintEvent(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *EventBlockRewardsToppedUp) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EventBlockRewardsToppedUp) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EventBlockRewardsToppedUp) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.OraclePaid.Size()
		i -= size
		if _, err := m.OraclePaid.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintEvent(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x3a
	{
		size := m.ValidatorPaid.Size()
		i -= size
		if _, err := m.ValidatorPaid.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintEvent(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x32
	{
		size := m.OracleOrganic.Size()
		i -= size
		if _, err := m.OracleOrganic.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintEvent(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x2a
	{
		size := m.ValidatorOrganic.Size()
		i -= size
		if _, err := m.ValidatorOrganic.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintEvent(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	{
		size := m.OracleTarget.Size()
		i -= size
		if _, err := m.OracleTarget.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintEvent(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	{
		size := m.ValidatorTarget.Size()
		i -= size
		if _, err := m.ValidatorTarget.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintEvent(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.Denom) > 0 {
		i -= len(m.Denom)
		copy(dAtA[i:], m.Denom)
		i = encodeVarintEvent(dAtA, i, uint64(len(m.Denom)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *EventUnpricedStabilityTaxRouted) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EventUnpricedStabilityTaxRouted) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EventUnpricedStabilityTaxRouted) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Deferred) > 0 {
		for iNdEx := len(m.Deferred) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Deferred[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintEvent(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.Moved) > 0 {
		for iNdEx := len(m.Moved) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Moved[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintEvent(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *EventLiabilityIncomplete) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EventLiabilityIncomplete) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EventLiabilityIncomplete) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.UntrustedSuspendedSupply) > 0 {
		for iNdEx := len(m.UntrustedSuspendedSupply) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.UntrustedSuspendedSupply[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintEvent(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.StaleMemberSupply) > 0 {
		for iNdEx := len(m.StaleMemberSupply) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.StaleMemberSupply[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintEvent(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	{
		size, err := m.ClaimableLiability.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintEvent(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *EventExpansionAllocated) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EventExpansionAllocated) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EventExpansionAllocated) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.OverflowBurn.Size()
		i -= size
		if _, err := m.OverflowBurn.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintEvent(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x32
	{
		size := m.SpreadAndDustBurn.Size()
		i -= size
		if _, err := m.SpreadAndDustBurn.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintEvent(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x2a
	{
		size := m.InsuranceCredit.Size()
		i -= size
		if _, err := m.InsuranceCredit.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintEvent(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	{
		size := m.StrategicReserveCredit.Size()
		i -= size
		if _, err := m.StrategicReserveCredit.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintEvent(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	{
		size := m.RedemptionBufferCredit.Size()
		i -= size
		if _, err := m.RedemptionBufferCredit.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintEvent(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.Denom) > 0 {
		i -= len(m.Denom)
		copy(dAtA[i:], m.Denom)
		i = encodeVarintEvent(dAtA, i, uint64(len(m.Denom)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *EventRedemptionBufferDrawn) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EventRedemptionBufferDrawn) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EventRedemptionBufferDrawn) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.Payment.Size()
		i -= size
		if _, err := m.Payment.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintEvent(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.Denom) > 0 {
		i -= len(m.Denom)
		copy(dAtA[i:], m.Denom)
		i = encodeVarintEvent(dAtA, i, uint64(len(m.Denom)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *EventMonetaryMandateSet) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EventMonetaryMandateSet) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EventMonetaryMandateSet) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.ExpiryHeight != 0 {
		i = encodeVarintEvent(dAtA, i, uint64(m.ExpiryHeight))
		i--
		dAtA[i] = 0x20
	}
	if m.ActivationHeight != 0 {
		i = encodeVarintEvent(dAtA, i, uint64(m.ActivationHeight))
		i--
		dAtA[i] = 0x18
	}
	if len(m.Committee) > 0 {
		i -= len(m.Committee)
		copy(dAtA[i:], m.Committee)
		i = encodeVarintEvent(dAtA, i, uint64(len(m.Committee)))
		i--
		dAtA[i] = 0x12
	}
	if m.Term != 0 {
		i = encodeVarintEvent(dAtA, i, uint64(m.Term))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *EventReferenceTaxCapRebased) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EventReferenceTaxCapRebased) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EventReferenceTaxCapRebased) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.NewCap.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintEvent(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	{
		size, err := m.OldCap.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintEvent(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintEvent(dAtA []byte, offset int, v uint64) int {
	offset -= sovEvent(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *EventTaxCapsUpdated) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.TaxCaps) > 0 {
		for _, e := range m.TaxCaps {
			l = e.Size()
			n += 1 + l + sovEvent(uint64(l))
		}
	}
	return n
}

func (m *EventBlockRewardsToppedUp) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Denom)
	if l > 0 {
		n += 1 + l + sovEvent(uint64(l))
	}
	l = m.ValidatorTarget.Size()
	n += 1 + l + sovEvent(uint64(l))
	l = m.OracleTarget.Size()
	n += 1 + l + sovEvent(uint64(l))
	l = m.ValidatorOrganic.Size()
	n += 1 + l + sovEvent(uint64(l))
	l = m.OracleOrganic.Size()
	n += 1 + l + sovEvent(uint64(l))
	l = m.ValidatorPaid.Size()
	n += 1 + l + sovEvent(uint64(l))
	l = m.OraclePaid.Size()
	n += 1 + l + sovEvent(uint64(l))
	return n
}

func (m *EventUnpricedStabilityTaxRouted) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Moved) > 0 {
		for _, e := range m.Moved {
			l = e.Size()
			n += 1 + l + sovEvent(uint64(l))
		}
	}
	if len(m.Deferred) > 0 {
		for _, e := range m.Deferred {
			l = e.Size()
			n += 1 + l + sovEvent(uint64(l))
		}
	}
	return n
}

func (m *EventLiabilityIncomplete) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.ClaimableLiability.Size()
	n += 1 + l + sovEvent(uint64(l))
	if len(m.StaleMemberSupply) > 0 {
		for _, e := range m.StaleMemberSupply {
			l = e.Size()
			n += 1 + l + sovEvent(uint64(l))
		}
	}
	if len(m.UntrustedSuspendedSupply) > 0 {
		for _, e := range m.UntrustedSuspendedSupply {
			l = e.Size()
			n += 1 + l + sovEvent(uint64(l))
		}
	}
	return n
}

func (m *EventExpansionAllocated) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Denom)
	if l > 0 {
		n += 1 + l + sovEvent(uint64(l))
	}
	l = m.RedemptionBufferCredit.Size()
	n += 1 + l + sovEvent(uint64(l))
	l = m.StrategicReserveCredit.Size()
	n += 1 + l + sovEvent(uint64(l))
	l = m.InsuranceCredit.Size()
	n += 1 + l + sovEvent(uint64(l))
	l = m.SpreadAndDustBurn.Size()
	n += 1 + l + sovEvent(uint64(l))
	l = m.OverflowBurn.Size()
	n += 1 + l + sovEvent(uint64(l))
	return n
}

func (m *EventRedemptionBufferDrawn) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Denom)
	if l > 0 {
		n += 1 + l + sovEvent(uint64(l))
	}
	l = m.Payment.Size()
	n += 1 + l + sovEvent(uint64(l))
	return n
}

func (m *EventMonetaryMandateSet) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Term != 0 {
		n += 1 + sovEvent(uint64(m.Term))
	}
	l = len(m.Committee)
	if l > 0 {
		n += 1 + l + sovEvent(uint64(l))
	}
	if m.ActivationHeight != 0 {
		n += 1 + sovEvent(uint64(m.ActivationHeight))
	}
	if m.ExpiryHeight != 0 {
		n += 1 + sovEvent(uint64(m.ExpiryHeight))
	}
	return n
}

func (m *EventReferenceTaxCapRebased) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.OldCap.Size()
	n += 1 + l + sovEvent(uint64(l))
	l = m.NewCap.Size()
	n += 1 + l + sovEvent(uint64(l))
	return n
}

func sovEvent(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozEvent(x uint64) (n int) {
	return sovEvent(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *EventTaxCapsUpdated) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEvent
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EventTaxCapsUpdated: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EventTaxCapsUpdated: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TaxCaps", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TaxCaps = append(m.TaxCaps, TaxCap{})
			if err := m.TaxCaps[len(m.TaxCaps)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipEvent(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEvent
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *EventBlockRewardsToppedUp) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEvent
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EventBlockRewardsToppedUp: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EventBlockRewardsToppedUp: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Denom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Denom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ValidatorTarget", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ValidatorTarget.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OracleTarget", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.OracleTarget.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ValidatorOrganic", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ValidatorOrganic.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OracleOrganic", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.OracleOrganic.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ValidatorPaid", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ValidatorPaid.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OraclePaid", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.OraclePaid.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipEvent(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEvent
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *EventUnpricedStabilityTaxRouted) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEvent
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EventUnpricedStabilityTaxRouted: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EventUnpricedStabilityTaxRouted: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Moved", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Moved = append(m.Moved, types.Coin{})
			if err := m.Moved[len(m.Moved)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Deferred", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Deferred = append(m.Deferred, types.Coin{})
			if err := m.Deferred[len(m.Deferred)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipEvent(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEvent
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *EventLiabilityIncomplete) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEvent
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EventLiabilityIncomplete: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EventLiabilityIncomplete: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ClaimableLiability", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ClaimableLiability.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StaleMemberSupply", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.StaleMemberSupply = append(m.StaleMemberSupply, types.Coin{})
			if err := m.StaleMemberSupply[len(m.StaleMemberSupply)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UntrustedSuspendedSupply", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.UntrustedSuspendedSupply = append(m.UntrustedSuspendedSupply, types.Coin{})
			if err := m.UntrustedSuspendedSupply[len(m.UntrustedSuspendedSupply)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipEvent(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEvent
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *EventExpansionAllocated) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEvent
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EventExpansionAllocated: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EventExpansionAllocated: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Denom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Denom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RedemptionBufferCredit", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.RedemptionBufferCredit.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StrategicReserveCredit", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.StrategicReserveCredit.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field InsuranceCredit", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.InsuranceCredit.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SpreadAndDustBurn", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.SpreadAndDustBurn.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OverflowBurn", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.OverflowBurn.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipEvent(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEvent
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *EventRedemptionBufferDrawn) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEvent
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EventRedemptionBufferDrawn: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EventRedemptionBufferDrawn: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Denom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Denom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Payment", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Payment.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipEvent(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEvent
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *EventMonetaryMandateSet) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEvent
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EventMonetaryMandateSet: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EventMonetaryMandateSet: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Term", wireType)
			}
			m.Term = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Term |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Committee", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Committee = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ActivationHeight", wireType)
			}
			m.ActivationHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ActivationHeight |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ExpiryHeight", wireType)
			}
			m.ExpiryHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ExpiryHeight |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipEvent(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEvent
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *EventReferenceTaxCapRebased) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEvent
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EventReferenceTaxCapRebased: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EventReferenceTaxCapRebased: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OldCap", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.OldCap.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NewCap", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.NewCap.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipEvent(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEvent
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipEvent(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowEvent
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthEvent
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupEvent
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthEvent
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthEvent        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowEvent          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupEvent = fmt.Errorf("proto: unexpected end of group")
)
