syntax = "proto3";

package noah.treasury.module.v1;

import "cosmos/app/v1alpha1/module.proto";

// Module is the config object for the treasury module.
message Module {
  option (cosmos.app.v1alpha1.module) = {
    go_import : "noah/x/treasury"
  };

  // authority defines the custom module authority. If not set, defaults to the
  // governance module.
  string authority = 1;

  // reward_collector_name defines the module account name to which
  // seigniorage reward is sent. If not set, defaults to "oracle".
  string reward_collector_name = 2;
}
