syntax = "proto3";
package noah.market.v1;

import "amino/amino.proto";
import "cosmos/base/v1beta1/coin.proto";
import "cosmos/query/v1/query.proto";
import "cosmos_proto/cosmos.proto";
import "gogoproto/gogo.proto";
import "google/api/annotations.proto";
import "noah/market/v1/market.proto";

option go_package = "noah/x/market/types";

// Query defines the gRPC querier service.
service Query {
  // Swap returns simulated swap amount.
  rpc Swap(QuerySwapRequest) returns (QuerySwapResponse) {
    option (cosmos.query.v1.module_query_safe) = true;
    option (google.api.http).get = "/noah/market/v1/swap";
  }

  // NoahPoolDelta returns noah_pool_delta amount.
  rpc NoahPoolDelta(QueryNoahPoolDeltaRequest)
      returns (QueryNoahPoolDeltaResponse) {
    option (cosmos.query.v1.module_query_safe) = true;
    option (google.api.http).get = "/noah/market/v1/noah_pool_delta";
  }

  // Params queries all parameters.
  rpc Params(QueryParamsRequest) returns (QueryParamsResponse) {
    option (cosmos.query.v1.module_query_safe) = true;
    option (google.api.http).get = "/noah/market/v1/params";
  }
}

// QuerySwapRequest is the request type for the Query/Swap RPC method.
message QuerySwapRequest {
  // offer_coin defines the coin being offered (i.e. 1000000uark)
  string offer_coin = 1;
  // ask_denom defines the denom of the coin to swap to
  string ask_denom = 2;
}

// QuerySwapResponse is the response type for the Query/Swap RPC method.
message QuerySwapResponse {
  // return_coin defines the coin returned as a result of the swap simulation.
  cosmos.base.v1beta1.Coin return_coin = 1 [ (gogoproto.nullable) = false ];
}

// QueryNoahPoolDeltaRequest is the request type for the Query/NoahPoolDelta RPC
// method.
message QueryNoahPoolDeltaRequest {}

// QueryNoahPoolDeltaResponse is the response type for the Query/NoahPoolDelta
// RPC method.
message QueryNoahPoolDeltaResponse {
  // noah_pool_delta defines the gap between the NoahPool and the NoahBasePool
  string noah_pool_delta = 1 [
    (cosmos_proto.scalar) = "cosmos.Dec",
    (gogoproto.customtype) = "cosmossdk.io/math.LegacyDec",
    (gogoproto.nullable) = false,
    (amino.dont_omitempty) = true
  ];
}

// QueryParamsRequest is the request type for the Query/Params RPC method.
message QueryParamsRequest {}

// QueryParamsResponse is the response type for the Query/Params RPC method.
message QueryParamsResponse {
  // params defines the parameters of the module.
  Params params = 1
      [ (gogoproto.nullable) = false, (amino.dont_omitempty) = true ];
}
