syntax = "proto3";
package noah.treasury.v1;

import "amino/amino.proto";
import "cosmos/base/v1beta1/coin.proto";
import "cosmos_proto/cosmos.proto";
import "gogoproto/gogo.proto";
import "noah/treasury/v1/treasury.proto";

option go_package = "noah/x/treasury/types";

// GenesisState defines the treasury module's genesis state.
message GenesisState {
  Params params = 1
      [ (gogoproto.nullable) = false, (amino.dont_omitempty) = true ];
  string tax_rate = 2 [
    (cosmos_proto.scalar) = "cosmos.Dec",
    (gogoproto.customtype) = "cosmossdk.io/math.LegacyDec",
    (gogoproto.nullable) = false,
    (amino.dont_omitempty) = true
  ];
  string reward_weight = 3 [
    (cosmos_proto.scalar) = "cosmos.Dec",
    (gogoproto.customtype) = "cosmossdk.io/math.LegacyDec",
    (gogoproto.nullable) = false,
    (amino.dont_omitempty) = true
  ];
  repeated TaxCap tax_caps = 4
      [ (gogoproto.nullable) = false, (amino.dont_omitempty) = true ];
  repeated cosmos.base.v1beta1.Coin epoch_tax_proceeds = 5 [
    (gogoproto.nullable) = false,
    (gogoproto.castrepeated) = "github.com/cosmos/cosmos-sdk/types.Coins",
    (amino.dont_omitempty) = true,
    (amino.encoding) = "legacy_coins"
  ];
  repeated cosmos.base.v1beta1.Coin epoch_initial_issuance = 6 [
    (gogoproto.nullable) = false,
    (gogoproto.castrepeated) = "github.com/cosmos/cosmos-sdk/types.Coins",
    (amino.dont_omitempty) = true,
    (amino.encoding) = "legacy_coins"
  ];
  repeated EpochState epoch_states = 7
      [ (gogoproto.nullable) = false, (amino.dont_omitempty) = true ];
}

// EpochState is the record for each epoch state
message EpochState {
  uint64 epoch = 1;
  string tax_reward = 2 [
    (cosmos_proto.scalar) = "cosmos.Dec",
    (gogoproto.customtype) = "cosmossdk.io/math.LegacyDec",
    (gogoproto.nullable) = false,
    (amino.dont_omitempty) = true
  ];
  string seigniorage_reward = 3 [
    (cosmos_proto.scalar) = "cosmos.Dec",
    (gogoproto.customtype) = "cosmossdk.io/math.LegacyDec",
    (gogoproto.nullable) = false,
    (amino.dont_omitempty) = true
  ];
  string total_staked_ark = 4 [
    (cosmos_proto.scalar) = "cosmos.Int",
    (gogoproto.customtype) = "cosmossdk.io/math.Int",
    (gogoproto.nullable) = false,
    (amino.dont_omitempty) = true
  ];
}

// EpochTaxProceeds represents the tax amount
// collected at the current epoch
message EpochTaxProceeds {
  repeated cosmos.base.v1beta1.Coin tax_proceeds = 1 [
    (gogoproto.moretags) = "yaml:\"tax_proceeds\"",
    (gogoproto.castrepeated) = "github.com/cosmos/cosmos-sdk/types.Coins",
    (gogoproto.nullable) = false,
    (amino.encoding) = "legacy_coins"
  ];
}

// EpochInitialIssuance represents initial issuance
// of the currrent epoch
message EpochInitialIssuance {
  repeated cosmos.base.v1beta1.Coin issuance = 1 [
    (gogoproto.moretags) = "yaml:\"issuance\"",
    (gogoproto.castrepeated) = "github.com/cosmos/cosmos-sdk/types.Coins",
    (gogoproto.nullable) = false,
    (amino.encoding) = "legacy_coins"
  ];
}
