// Code generated by protoc-gen-go-pulsar. DO NOT EDIT.
package marketv1

import (
	_ "cosmossdk.io/api/amino"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	runtime "github.com/cosmos/cosmos-proto/runtime"
	_ "github.com/cosmos/gogoproto/gogoproto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoiface "google.golang.org/protobuf/runtime/protoiface"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	io "io"
	reflect "reflect"
	sync "sync"
)

var (
	md_EventSwap              protoreflect.MessageDescriptor
	fd_EventSwap_trader       protoreflect.FieldDescriptor
	fd_EventSwap_recipient    protoreflect.FieldDescriptor
	fd_EventSwap_offer_denom  protoreflect.FieldDescriptor
	fd_EventSwap_offer_amount protoreflect.FieldDescriptor
	fd_EventSwap_swap_denom   protoreflect.FieldDescriptor
	fd_EventSwap_swap_amount  protoreflect.FieldDescriptor
	fd_EventSwap_fee_denom    protoreflect.FieldDescriptor
	fd_EventSwap_fee_amount   protoreflect.FieldDescriptor
)

func init() {
	file_ark_market_v1_event_proto_init()
	md_EventSwap = File_ark_market_v1_event_proto.Messages().ByName("EventSwap")
	fd_EventSwap_trader = md_EventSwap.Fields().ByName("trader")
	fd_EventSwap_recipient = md_EventSwap.Fields().ByName("recipient")
	fd_EventSwap_offer_denom = md_EventSwap.Fields().ByName("offer_denom")
	fd_EventSwap_offer_amount = md_EventSwap.Fields().ByName("offer_amount")
	fd_EventSwap_swap_denom = md_EventSwap.Fields().ByName("swap_denom")
	fd_EventSwap_swap_amount = md_EventSwap.Fields().ByName("swap_amount")
	fd_EventSwap_fee_denom = md_EventSwap.Fields().ByName("fee_denom")
	fd_EventSwap_fee_amount = md_EventSwap.Fields().ByName("fee_amount")
}

var _ protoreflect.Message = (*fastReflection_EventSwap)(nil)

type fastReflection_EventSwap EventSwap

func (x *EventSwap) ProtoReflect() protoreflect.Message {
	return (*fastReflection_EventSwap)(x)
}

func (x *EventSwap) slowProtoReflect() protoreflect.Message {
	mi := &file_ark_market_v1_event_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

var _fastReflection_EventSwap_messageType fastReflection_EventSwap_messageType
var _ protoreflect.MessageType = fastReflection_EventSwap_messageType{}

type fastReflection_EventSwap_messageType struct{}

func (x fastReflection_EventSwap_messageType) Zero() protoreflect.Message {
	return (*fastReflection_EventSwap)(nil)
}
func (x fastReflection_EventSwap_messageType) New() protoreflect.Message {
	return new(fastReflection_EventSwap)
}
func (x fastReflection_EventSwap_messageType) Descriptor() protoreflect.MessageDescriptor {
	return md_EventSwap
}

// Descriptor returns message descriptor, which contains only the protobuf
// type information for the message.
func (x *fastReflection_EventSwap) Descriptor() protoreflect.MessageDescriptor {
	return md_EventSwap
}

// Type returns the message type, which encapsulates both Go and protobuf
// type information. If the Go type information is not needed,
// it is recommended that the message descriptor be used instead.
func (x *fastReflection_EventSwap) Type() protoreflect.MessageType {
	return _fastReflection_EventSwap_messageType
}

// New returns a newly allocated and mutable empty message.
func (x *fastReflection_EventSwap) New() protoreflect.Message {
	return new(fastReflection_EventSwap)
}

// Interface unwraps the message reflection interface and
// returns the underlying ProtoMessage interface.
func (x *fastReflection_EventSwap) Interface() protoreflect.ProtoMessage {
	return (*EventSwap)(x)
}

// Range iterates over every populated field in an undefined order,
// calling f for each field descriptor and value encountered.
// Range returns immediately if f returns false.
// While iterating, mutating operations may only be performed
// on the current field descriptor.
func (x *fastReflection_EventSwap) Range(f func(protoreflect.FieldDescriptor, protoreflect.Value) bool) {
	if x.Trader != "" {
		value := protoreflect.ValueOfString(x.Trader)
		if !f(fd_EventSwap_trader, value) {
			return
		}
	}
	if x.Recipient != "" {
		value := protoreflect.ValueOfString(x.Recipient)
		if !f(fd_EventSwap_recipient, value) {
			return
		}
	}
	if x.OfferDenom != "" {
		value := protoreflect.ValueOfString(x.OfferDenom)
		if !f(fd_EventSwap_offer_denom, value) {
			return
		}
	}
	if x.OfferAmount != "" {
		value := protoreflect.ValueOfString(x.OfferAmount)
		if !f(fd_EventSwap_offer_amount, value) {
			return
		}
	}
	if x.SwapDenom != "" {
		value := protoreflect.ValueOfString(x.SwapDenom)
		if !f(fd_EventSwap_swap_denom, value) {
			return
		}
	}
	if x.SwapAmount != "" {
		value := protoreflect.ValueOfString(x.SwapAmount)
		if !f(fd_EventSwap_swap_amount, value) {
			return
		}
	}
	if x.FeeDenom != "" {
		value := protoreflect.ValueOfString(x.FeeDenom)
		if !f(fd_EventSwap_fee_denom, value) {
			return
		}
	}
	if x.FeeAmount != "" {
		value := protoreflect.ValueOfString(x.FeeAmount)
		if !f(fd_EventSwap_fee_amount, value) {
			return
		}
	}
}

// Has reports whether a field is populated.
//
// Some fields have the property of nullability where it is possible to
// distinguish between the default value of a field and whether the field
// was explicitly populated with the default value. Singular message fields,
// member fields of a oneof, and proto2 scalar fields are nullable. Such
// fields are populated only if explicitly set.
//
// In other cases (aside from the nullable cases above),
// a proto3 scalar field is populated if it contains a non-zero value, and
// a repeated field is populated if it is non-empty.
func (x *fastReflection_EventSwap) Has(fd protoreflect.FieldDescriptor) bool {
	switch fd.FullName() {
	case "ark.market.v1.EventSwap.trader":
		return x.Trader != ""
	case "ark.market.v1.EventSwap.recipient":
		return x.Recipient != ""
	case "ark.market.v1.EventSwap.offer_denom":
		return x.OfferDenom != ""
	case "ark.market.v1.EventSwap.offer_amount":
		return x.OfferAmount != ""
	case "ark.market.v1.EventSwap.swap_denom":
		return x.SwapDenom != ""
	case "ark.market.v1.EventSwap.swap_amount":
		return x.SwapAmount != ""
	case "ark.market.v1.EventSwap.fee_denom":
		return x.FeeDenom != ""
	case "ark.market.v1.EventSwap.fee_amount":
		return x.FeeAmount != ""
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: ark.market.v1.EventSwap"))
		}
		panic(fmt.Errorf("message ark.market.v1.EventSwap does not contain field %s", fd.FullName()))
	}
}

// Clear clears the field such that a subsequent Has call reports false.
//
// Clearing an extension field clears both the extension type and value
// associated with the given field number.
//
// Clear is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_EventSwap) Clear(fd protoreflect.FieldDescriptor) {
	switch fd.FullName() {
	case "ark.market.v1.EventSwap.trader":
		x.Trader = ""
	case "ark.market.v1.EventSwap.recipient":
		x.Recipient = ""
	case "ark.market.v1.EventSwap.offer_denom":
		x.OfferDenom = ""
	case "ark.market.v1.EventSwap.offer_amount":
		x.OfferAmount = ""
	case "ark.market.v1.EventSwap.swap_denom":
		x.SwapDenom = ""
	case "ark.market.v1.EventSwap.swap_amount":
		x.SwapAmount = ""
	case "ark.market.v1.EventSwap.fee_denom":
		x.FeeDenom = ""
	case "ark.market.v1.EventSwap.fee_amount":
		x.FeeAmount = ""
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: ark.market.v1.EventSwap"))
		}
		panic(fmt.Errorf("message ark.market.v1.EventSwap does not contain field %s", fd.FullName()))
	}
}

// Get retrieves the value for a field.
//
// For unpopulated scalars, it returns the default value, where
// the default value of a bytes scalar is guaranteed to be a copy.
// For unpopulated composite types, it returns an empty, read-only view
// of the value; to obtain a mutable reference, use Mutable.
func (x *fastReflection_EventSwap) Get(descriptor protoreflect.FieldDescriptor) protoreflect.Value {
	switch descriptor.FullName() {
	case "ark.market.v1.EventSwap.trader":
		value := x.Trader
		return protoreflect.ValueOfString(value)
	case "ark.market.v1.EventSwap.recipient":
		value := x.Recipient
		return protoreflect.ValueOfString(value)
	case "ark.market.v1.EventSwap.offer_denom":
		value := x.OfferDenom
		return protoreflect.ValueOfString(value)
	case "ark.market.v1.EventSwap.offer_amount":
		value := x.OfferAmount
		return protoreflect.ValueOfString(value)
	case "ark.market.v1.EventSwap.swap_denom":
		value := x.SwapDenom
		return protoreflect.ValueOfString(value)
	case "ark.market.v1.EventSwap.swap_amount":
		value := x.SwapAmount
		return protoreflect.ValueOfString(value)
	case "ark.market.v1.EventSwap.fee_denom":
		value := x.FeeDenom
		return protoreflect.ValueOfString(value)
	case "ark.market.v1.EventSwap.fee_amount":
		value := x.FeeAmount
		return protoreflect.ValueOfString(value)
	default:
		if descriptor.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: ark.market.v1.EventSwap"))
		}
		panic(fmt.Errorf("message ark.market.v1.EventSwap does not contain field %s", descriptor.FullName()))
	}
}

// Set stores the value for a field.
//
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType.
// When setting a composite type, it is unspecified whether the stored value
// aliases the source's memory in any way. If the composite value is an
// empty, read-only value, then it panics.
//
// Set is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_EventSwap) Set(fd protoreflect.FieldDescriptor, value protoreflect.Value) {
	switch fd.FullName() {
	case "ark.market.v1.EventSwap.trader":
		x.Trader = value.Interface().(string)
	case "ark.market.v1.EventSwap.recipient":
		x.Recipient = value.Interface().(string)
	case "ark.market.v1.EventSwap.offer_denom":
		x.OfferDenom = value.Interface().(string)
	case "ark.market.v1.EventSwap.offer_amount":
		x.OfferAmount = value.Interface().(string)
	case "ark.market.v1.EventSwap.swap_denom":
		x.SwapDenom = value.Interface().(string)
	case "ark.market.v1.EventSwap.swap_amount":
		x.SwapAmount = value.Interface().(string)
	case "ark.market.v1.EventSwap.fee_denom":
		x.FeeDenom = value.Interface().(string)
	case "ark.market.v1.EventSwap.fee_amount":
		x.FeeAmount = value.Interface().(string)
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: ark.market.v1.EventSwap"))
		}
		panic(fmt.Errorf("message ark.market.v1.EventSwap does not contain field %s", fd.FullName()))
	}
}

// Mutable returns a mutable reference to a composite type.
//
// If the field is unpopulated, it may allocate a composite value.
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType
// if not already stored.
// It panics if the field does not contain a composite type.
//
// Mutable is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_EventSwap) Mutable(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "ark.market.v1.EventSwap.trader":
		panic(fmt.Errorf("field trader of message ark.market.v1.EventSwap is not mutable"))
	case "ark.market.v1.EventSwap.recipient":
		panic(fmt.Errorf("field recipient of message ark.market.v1.EventSwap is not mutable"))
	case "ark.market.v1.EventSwap.offer_denom":
		panic(fmt.Errorf("field offer_denom of message ark.market.v1.EventSwap is not mutable"))
	case "ark.market.v1.EventSwap.offer_amount":
		panic(fmt.Errorf("field offer_amount of message ark.market.v1.EventSwap is not mutable"))
	case "ark.market.v1.EventSwap.swap_denom":
		panic(fmt.Errorf("field swap_denom of message ark.market.v1.EventSwap is not mutable"))
	case "ark.market.v1.EventSwap.swap_amount":
		panic(fmt.Errorf("field swap_amount of message ark.market.v1.EventSwap is not mutable"))
	case "ark.market.v1.EventSwap.fee_denom":
		panic(fmt.Errorf("field fee_denom of message ark.market.v1.EventSwap is not mutable"))
	case "ark.market.v1.EventSwap.fee_amount":
		panic(fmt.Errorf("field fee_amount of message ark.market.v1.EventSwap is not mutable"))
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: ark.market.v1.EventSwap"))
		}
		panic(fmt.Errorf("message ark.market.v1.EventSwap does not contain field %s", fd.FullName()))
	}
}

// NewField returns a new value that is assignable to the field
// for the given descriptor. For scalars, this returns the default value.
// For lists, maps, and messages, this returns a new, empty, mutable value.
func (x *fastReflection_EventSwap) NewField(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "ark.market.v1.EventSwap.trader":
		return protoreflect.ValueOfString("")
	case "ark.market.v1.EventSwap.recipient":
		return protoreflect.ValueOfString("")
	case "ark.market.v1.EventSwap.offer_denom":
		return protoreflect.ValueOfString("")
	case "ark.market.v1.EventSwap.offer_amount":
		return protoreflect.ValueOfString("")
	case "ark.market.v1.EventSwap.swap_denom":
		return protoreflect.ValueOfString("")
	case "ark.market.v1.EventSwap.swap_amount":
		return protoreflect.ValueOfString("")
	case "ark.market.v1.EventSwap.fee_denom":
		return protoreflect.ValueOfString("")
	case "ark.market.v1.EventSwap.fee_amount":
		return protoreflect.ValueOfString("")
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: ark.market.v1.EventSwap"))
		}
		panic(fmt.Errorf("message ark.market.v1.EventSwap does not contain field %s", fd.FullName()))
	}
}

// WhichOneof reports which field within the oneof is populated,
// returning nil if none are populated.
// It panics if the oneof descriptor does not belong to this message.
func (x *fastReflection_EventSwap) WhichOneof(d protoreflect.OneofDescriptor) protoreflect.FieldDescriptor {
	switch d.FullName() {
	default:
		panic(fmt.Errorf("%s is not a oneof field in ark.market.v1.EventSwap", d.FullName()))
	}
	panic("unreachable")
}

// GetUnknown retrieves the entire list of unknown fields.
// The caller may only mutate the contents of the RawFields
// if the mutated bytes are stored back into the message with SetUnknown.
func (x *fastReflection_EventSwap) GetUnknown() protoreflect.RawFields {
	return x.unknownFields
}

// SetUnknown stores an entire list of unknown fields.
// The raw fields must be syntactically valid according to the wire format.
// An implementation may panic if this is not the case.
// Once stored, the caller must not mutate the content of the RawFields.
// An empty RawFields may be passed to clear the fields.
//
// SetUnknown is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_EventSwap) SetUnknown(fields protoreflect.RawFields) {
	x.unknownFields = fields
}

// IsValid reports whether the message is valid.
//
// An invalid message is an empty, read-only value.
//
// An invalid message often corresponds to a nil pointer of the concrete
// message type, but the details are implementation dependent.
// Validity is not part of the protobuf data model, and may not
// be preserved in marshaling or other operations.
func (x *fastReflection_EventSwap) IsValid() bool {
	return x != nil
}

// ProtoMethods returns optional fastReflectionFeature-path implementations of various operations.
// This method may return nil.
//
// The returned methods type is identical to
// "google.golang.org/protobuf/runtime/protoiface".Methods.
// Consult the protoiface package documentation for details.
func (x *fastReflection_EventSwap) ProtoMethods() *protoiface.Methods {
	size := func(input protoiface.SizeInput) protoiface.SizeOutput {
		x := input.Message.Interface().(*EventSwap)
		if x == nil {
			return protoiface.SizeOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Size:              0,
			}
		}
		options := runtime.SizeInputToOptions(input)
		_ = options
		var n int
		var l int
		_ = l
		l = len(x.Trader)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.Recipient)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.OfferDenom)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.OfferAmount)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.SwapDenom)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.SwapAmount)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.FeeDenom)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.FeeAmount)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		if x.unknownFields != nil {
			n += len(x.unknownFields)
		}
		return protoiface.SizeOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Size:              n,
		}
	}

	marshal := func(input protoiface.MarshalInput) (protoiface.MarshalOutput, error) {
		x := input.Message.Interface().(*EventSwap)
		if x == nil {
			return protoiface.MarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Buf:               input.Buf,
			}, nil
		}
		options := runtime.MarshalInputToOptions(input)
		_ = options
		size := options.Size(x)
		dAtA := make([]byte, size)
		i := len(dAtA)
		_ = i
		var l int
		_ = l
		if x.unknownFields != nil {
			i -= len(x.unknownFields)
			copy(dAtA[i:], x.unknownFields)
		}
		if len(x.FeeAmount) > 0 {
			i -= len(x.FeeAmount)
			copy(dAtA[i:], x.FeeAmount)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.FeeAmount)))
			i--
			dAtA[i] = 0x42
		}
		if len(x.FeeDenom) > 0 {
			i -= len(x.FeeDenom)
			copy(dAtA[i:], x.FeeDenom)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.FeeDenom)))
			i--
			dAtA[i] = 0x3a
		}
		if len(x.SwapAmount) > 0 {
			i -= len(x.SwapAmount)
			copy(dAtA[i:], x.SwapAmount)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.SwapAmount)))
			i--
			dAtA[i] = 0x32
		}
		if len(x.SwapDenom) > 0 {
			i -= len(x.SwapDenom)
			copy(dAtA[i:], x.SwapDenom)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.SwapDenom)))
			i--
			dAtA[i] = 0x2a
		}
		if len(x.OfferAmount) > 0 {
			i -= len(x.OfferAmount)
			copy(dAtA[i:], x.OfferAmount)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.OfferAmount)))
			i--
			dAtA[i] = 0x22
		}
		if len(x.OfferDenom) > 0 {
			i -= len(x.OfferDenom)
			copy(dAtA[i:], x.OfferDenom)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.OfferDenom)))
			i--
			dAtA[i] = 0x1a
		}
		if len(x.Recipient) > 0 {
			i -= len(x.Recipient)
			copy(dAtA[i:], x.Recipient)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.Recipient)))
			i--
			dAtA[i] = 0x12
		}
		if len(x.Trader) > 0 {
			i -= len(x.Trader)
			copy(dAtA[i:], x.Trader)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.Trader)))
			i--
			dAtA[i] = 0xa
		}
		if input.Buf != nil {
			input.Buf = append(input.Buf, dAtA...)
		} else {
			input.Buf = dAtA
		}
		return protoiface.MarshalOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Buf:               input.Buf,
		}, nil
	}
	unmarshal := func(input protoiface.UnmarshalInput) (protoiface.UnmarshalOutput, error) {
		x := input.Message.Interface().(*EventSwap)
		if x == nil {
			return protoiface.UnmarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Flags:             input.Flags,
			}, nil
		}
		options := runtime.UnmarshalInputToOptions(input)
		_ = options
		dAtA := input.Buf
		l := len(dAtA)
		iNdEx := 0
		for iNdEx < l {
			preIndex := iNdEx
			var wire uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
				}
				if iNdEx >= l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				wire |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			fieldNum := int32(wire >> 3)
			wireType := int(wire & 0x7)
			if wireType == 4 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: EventSwap: wiretype end group for non-group")
			}
			if fieldNum <= 0 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: EventSwap: illegal tag %d (wire type %d)", fieldNum, wire)
			}
			switch fieldNum {
			case 1:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Trader", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.Trader = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 2:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Recipient", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.Recipient = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 3:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field OfferDenom", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.OfferDenom = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 4:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field OfferAmount", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.OfferAmount = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 5:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field SwapDenom", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.SwapDenom = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 6:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field SwapAmount", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.SwapAmount = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 7:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field FeeDenom", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.FeeDenom = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 8:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field FeeAmount", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.FeeAmount = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			default:
				iNdEx = preIndex
				skippy, err := runtime.Skip(dAtA[iNdEx:])
				if err != nil {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, err
				}
				if (skippy < 0) || (iNdEx+skippy) < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if (iNdEx + skippy) > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				if !options.DiscardUnknown {
					x.unknownFields = append(x.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
				}
				iNdEx += skippy
			}
		}

		if iNdEx > l {
			return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
		}
		return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, nil
	}
	return &protoiface.Methods{
		NoUnkeyedLiterals: struct{}{},
		Flags:             protoiface.SupportMarshalDeterministic | protoiface.SupportUnmarshalDiscardUnknown,
		Size:              size,
		Marshal:           marshal,
		Unmarshal:         unmarshal,
		Merge:             nil,
		CheckInitialized:  nil,
	}
}

var (
	md_EventPoolUpdated                      protoreflect.MessageDescriptor
	fd_EventPoolUpdated_old_base_pool_denom  protoreflect.FieldDescriptor
	fd_EventPoolUpdated_old_base_pool_amount protoreflect.FieldDescriptor
	fd_EventPoolUpdated_new_base_pool_denom  protoreflect.FieldDescriptor
	fd_EventPoolUpdated_new_base_pool_amount protoreflect.FieldDescriptor
	fd_EventPoolUpdated_old_ark_pool_delta   protoreflect.FieldDescriptor
	fd_EventPoolUpdated_new_ark_pool_delta   protoreflect.FieldDescriptor
)

func init() {
	file_ark_market_v1_event_proto_init()
	md_EventPoolUpdated = File_ark_market_v1_event_proto.Messages().ByName("EventPoolUpdated")
	fd_EventPoolUpdated_old_base_pool_denom = md_EventPoolUpdated.Fields().ByName("old_base_pool_denom")
	fd_EventPoolUpdated_old_base_pool_amount = md_EventPoolUpdated.Fields().ByName("old_base_pool_amount")
	fd_EventPoolUpdated_new_base_pool_denom = md_EventPoolUpdated.Fields().ByName("new_base_pool_denom")
	fd_EventPoolUpdated_new_base_pool_amount = md_EventPoolUpdated.Fields().ByName("new_base_pool_amount")
	fd_EventPoolUpdated_old_ark_pool_delta = md_EventPoolUpdated.Fields().ByName("old_ark_pool_delta")
	fd_EventPoolUpdated_new_ark_pool_delta = md_EventPoolUpdated.Fields().ByName("new_ark_pool_delta")
}

var _ protoreflect.Message = (*fastReflection_EventPoolUpdated)(nil)

type fastReflection_EventPoolUpdated EventPoolUpdated

func (x *EventPoolUpdated) ProtoReflect() protoreflect.Message {
	return (*fastReflection_EventPoolUpdated)(x)
}

func (x *EventPoolUpdated) slowProtoReflect() protoreflect.Message {
	mi := &file_ark_market_v1_event_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

var _fastReflection_EventPoolUpdated_messageType fastReflection_EventPoolUpdated_messageType
var _ protoreflect.MessageType = fastReflection_EventPoolUpdated_messageType{}

type fastReflection_EventPoolUpdated_messageType struct{}

func (x fastReflection_EventPoolUpdated_messageType) Zero() protoreflect.Message {
	return (*fastReflection_EventPoolUpdated)(nil)
}
func (x fastReflection_EventPoolUpdated_messageType) New() protoreflect.Message {
	return new(fastReflection_EventPoolUpdated)
}
func (x fastReflection_EventPoolUpdated_messageType) Descriptor() protoreflect.MessageDescriptor {
	return md_EventPoolUpdated
}

// Descriptor returns message descriptor, which contains only the protobuf
// type information for the message.
func (x *fastReflection_EventPoolUpdated) Descriptor() protoreflect.MessageDescriptor {
	return md_EventPoolUpdated
}

// Type returns the message type, which encapsulates both Go and protobuf
// type information. If the Go type information is not needed,
// it is recommended that the message descriptor be used instead.
func (x *fastReflection_EventPoolUpdated) Type() protoreflect.MessageType {
	return _fastReflection_EventPoolUpdated_messageType
}

// New returns a newly allocated and mutable empty message.
func (x *fastReflection_EventPoolUpdated) New() protoreflect.Message {
	return new(fastReflection_EventPoolUpdated)
}

// Interface unwraps the message reflection interface and
// returns the underlying ProtoMessage interface.
func (x *fastReflection_EventPoolUpdated) Interface() protoreflect.ProtoMessage {
	return (*EventPoolUpdated)(x)
}

// Range iterates over every populated field in an undefined order,
// calling f for each field descriptor and value encountered.
// Range returns immediately if f returns false.
// While iterating, mutating operations may only be performed
// on the current field descriptor.
func (x *fastReflection_EventPoolUpdated) Range(f func(protoreflect.FieldDescriptor, protoreflect.Value) bool) {
	if x.OldBasePoolDenom != "" {
		value := protoreflect.ValueOfString(x.OldBasePoolDenom)
		if !f(fd_EventPoolUpdated_old_base_pool_denom, value) {
			return
		}
	}
	if x.OldBasePoolAmount != "" {
		value := protoreflect.ValueOfString(x.OldBasePoolAmount)
		if !f(fd_EventPoolUpdated_old_base_pool_amount, value) {
			return
		}
	}
	if x.NewBasePoolDenom != "" {
		value := protoreflect.ValueOfString(x.NewBasePoolDenom)
		if !f(fd_EventPoolUpdated_new_base_pool_denom, value) {
			return
		}
	}
	if x.NewBasePoolAmount != "" {
		value := protoreflect.ValueOfString(x.NewBasePoolAmount)
		if !f(fd_EventPoolUpdated_new_base_pool_amount, value) {
			return
		}
	}
	if x.OldArkPoolDelta != "" {
		value := protoreflect.ValueOfString(x.OldArkPoolDelta)
		if !f(fd_EventPoolUpdated_old_ark_pool_delta, value) {
			return
		}
	}
	if x.NewArkPoolDelta != "" {
		value := protoreflect.ValueOfString(x.NewArkPoolDelta)
		if !f(fd_EventPoolUpdated_new_ark_pool_delta, value) {
			return
		}
	}
}

// Has reports whether a field is populated.
//
// Some fields have the property of nullability where it is possible to
// distinguish between the default value of a field and whether the field
// was explicitly populated with the default value. Singular message fields,
// member fields of a oneof, and proto2 scalar fields are nullable. Such
// fields are populated only if explicitly set.
//
// In other cases (aside from the nullable cases above),
// a proto3 scalar field is populated if it contains a non-zero value, and
// a repeated field is populated if it is non-empty.
func (x *fastReflection_EventPoolUpdated) Has(fd protoreflect.FieldDescriptor) bool {
	switch fd.FullName() {
	case "ark.market.v1.EventPoolUpdated.old_base_pool_denom":
		return x.OldBasePoolDenom != ""
	case "ark.market.v1.EventPoolUpdated.old_base_pool_amount":
		return x.OldBasePoolAmount != ""
	case "ark.market.v1.EventPoolUpdated.new_base_pool_denom":
		return x.NewBasePoolDenom != ""
	case "ark.market.v1.EventPoolUpdated.new_base_pool_amount":
		return x.NewBasePoolAmount != ""
	case "ark.market.v1.EventPoolUpdated.old_ark_pool_delta":
		return x.OldArkPoolDelta != ""
	case "ark.market.v1.EventPoolUpdated.new_ark_pool_delta":
		return x.NewArkPoolDelta != ""
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: ark.market.v1.EventPoolUpdated"))
		}
		panic(fmt.Errorf("message ark.market.v1.EventPoolUpdated does not contain field %s", fd.FullName()))
	}
}

// Clear clears the field such that a subsequent Has call reports false.
//
// Clearing an extension field clears both the extension type and value
// associated with the given field number.
//
// Clear is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_EventPoolUpdated) Clear(fd protoreflect.FieldDescriptor) {
	switch fd.FullName() {
	case "ark.market.v1.EventPoolUpdated.old_base_pool_denom":
		x.OldBasePoolDenom = ""
	case "ark.market.v1.EventPoolUpdated.old_base_pool_amount":
		x.OldBasePoolAmount = ""
	case "ark.market.v1.EventPoolUpdated.new_base_pool_denom":
		x.NewBasePoolDenom = ""
	case "ark.market.v1.EventPoolUpdated.new_base_pool_amount":
		x.NewBasePoolAmount = ""
	case "ark.market.v1.EventPoolUpdated.old_ark_pool_delta":
		x.OldArkPoolDelta = ""
	case "ark.market.v1.EventPoolUpdated.new_ark_pool_delta":
		x.NewArkPoolDelta = ""
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: ark.market.v1.EventPoolUpdated"))
		}
		panic(fmt.Errorf("message ark.market.v1.EventPoolUpdated does not contain field %s", fd.FullName()))
	}
}

// Get retrieves the value for a field.
//
// For unpopulated scalars, it returns the default value, where
// the default value of a bytes scalar is guaranteed to be a copy.
// For unpopulated composite types, it returns an empty, read-only view
// of the value; to obtain a mutable reference, use Mutable.
func (x *fastReflection_EventPoolUpdated) Get(descriptor protoreflect.FieldDescriptor) protoreflect.Value {
	switch descriptor.FullName() {
	case "ark.market.v1.EventPoolUpdated.old_base_pool_denom":
		value := x.OldBasePoolDenom
		return protoreflect.ValueOfString(value)
	case "ark.market.v1.EventPoolUpdated.old_base_pool_amount":
		value := x.OldBasePoolAmount
		return protoreflect.ValueOfString(value)
	case "ark.market.v1.EventPoolUpdated.new_base_pool_denom":
		value := x.NewBasePoolDenom
		return protoreflect.ValueOfString(value)
	case "ark.market.v1.EventPoolUpdated.new_base_pool_amount":
		value := x.NewBasePoolAmount
		return protoreflect.ValueOfString(value)
	case "ark.market.v1.EventPoolUpdated.old_ark_pool_delta":
		value := x.OldArkPoolDelta
		return protoreflect.ValueOfString(value)
	case "ark.market.v1.EventPoolUpdated.new_ark_pool_delta":
		value := x.NewArkPoolDelta
		return protoreflect.ValueOfString(value)
	default:
		if descriptor.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: ark.market.v1.EventPoolUpdated"))
		}
		panic(fmt.Errorf("message ark.market.v1.EventPoolUpdated does not contain field %s", descriptor.FullName()))
	}
}

// Set stores the value for a field.
//
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType.
// When setting a composite type, it is unspecified whether the stored value
// aliases the source's memory in any way. If the composite value is an
// empty, read-only value, then it panics.
//
// Set is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_EventPoolUpdated) Set(fd protoreflect.FieldDescriptor, value protoreflect.Value) {
	switch fd.FullName() {
	case "ark.market.v1.EventPoolUpdated.old_base_pool_denom":
		x.OldBasePoolDenom = value.Interface().(string)
	case "ark.market.v1.EventPoolUpdated.old_base_pool_amount":
		x.OldBasePoolAmount = value.Interface().(string)
	case "ark.market.v1.EventPoolUpdated.new_base_pool_denom":
		x.NewBasePoolDenom = value.Interface().(string)
	case "ark.market.v1.EventPoolUpdated.new_base_pool_amount":
		x.NewBasePoolAmount = value.Interface().(string)
	case "ark.market.v1.EventPoolUpdated.old_ark_pool_delta":
		x.OldArkPoolDelta = value.Interface().(string)
	case "ark.market.v1.EventPoolUpdated.new_ark_pool_delta":
		x.NewArkPoolDelta = value.Interface().(string)
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: ark.market.v1.EventPoolUpdated"))
		}
		panic(fmt.Errorf("message ark.market.v1.EventPoolUpdated does not contain field %s", fd.FullName()))
	}
}

// Mutable returns a mutable reference to a composite type.
//
// If the field is unpopulated, it may allocate a composite value.
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType
// if not already stored.
// It panics if the field does not contain a composite type.
//
// Mutable is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_EventPoolUpdated) Mutable(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "ark.market.v1.EventPoolUpdated.old_base_pool_denom":
		panic(fmt.Errorf("field old_base_pool_denom of message ark.market.v1.EventPoolUpdated is not mutable"))
	case "ark.market.v1.EventPoolUpdated.old_base_pool_amount":
		panic(fmt.Errorf("field old_base_pool_amount of message ark.market.v1.EventPoolUpdated is not mutable"))
	case "ark.market.v1.EventPoolUpdated.new_base_pool_denom":
		panic(fmt.Errorf("field new_base_pool_denom of message ark.market.v1.EventPoolUpdated is not mutable"))
	case "ark.market.v1.EventPoolUpdated.new_base_pool_amount":
		panic(fmt.Errorf("field new_base_pool_amount of message ark.market.v1.EventPoolUpdated is not mutable"))
	case "ark.market.v1.EventPoolUpdated.old_ark_pool_delta":
		panic(fmt.Errorf("field old_ark_pool_delta of message ark.market.v1.EventPoolUpdated is not mutable"))
	case "ark.market.v1.EventPoolUpdated.new_ark_pool_delta":
		panic(fmt.Errorf("field new_ark_pool_delta of message ark.market.v1.EventPoolUpdated is not mutable"))
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: ark.market.v1.EventPoolUpdated"))
		}
		panic(fmt.Errorf("message ark.market.v1.EventPoolUpdated does not contain field %s", fd.FullName()))
	}
}

// NewField returns a new value that is assignable to the field
// for the given descriptor. For scalars, this returns the default value.
// For lists, maps, and messages, this returns a new, empty, mutable value.
func (x *fastReflection_EventPoolUpdated) NewField(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "ark.market.v1.EventPoolUpdated.old_base_pool_denom":
		return protoreflect.ValueOfString("")
	case "ark.market.v1.EventPoolUpdated.old_base_pool_amount":
		return protoreflect.ValueOfString("")
	case "ark.market.v1.EventPoolUpdated.new_base_pool_denom":
		return protoreflect.ValueOfString("")
	case "ark.market.v1.EventPoolUpdated.new_base_pool_amount":
		return protoreflect.ValueOfString("")
	case "ark.market.v1.EventPoolUpdated.old_ark_pool_delta":
		return protoreflect.ValueOfString("")
	case "ark.market.v1.EventPoolUpdated.new_ark_pool_delta":
		return protoreflect.ValueOfString("")
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: ark.market.v1.EventPoolUpdated"))
		}
		panic(fmt.Errorf("message ark.market.v1.EventPoolUpdated does not contain field %s", fd.FullName()))
	}
}

// WhichOneof reports which field within the oneof is populated,
// returning nil if none are populated.
// It panics if the oneof descriptor does not belong to this message.
func (x *fastReflection_EventPoolUpdated) WhichOneof(d protoreflect.OneofDescriptor) protoreflect.FieldDescriptor {
	switch d.FullName() {
	default:
		panic(fmt.Errorf("%s is not a oneof field in ark.market.v1.EventPoolUpdated", d.FullName()))
	}
	panic("unreachable")
}

// GetUnknown retrieves the entire list of unknown fields.
// The caller may only mutate the contents of the RawFields
// if the mutated bytes are stored back into the message with SetUnknown.
func (x *fastReflection_EventPoolUpdated) GetUnknown() protoreflect.RawFields {
	return x.unknownFields
}

// SetUnknown stores an entire list of unknown fields.
// The raw fields must be syntactically valid according to the wire format.
// An implementation may panic if this is not the case.
// Once stored, the caller must not mutate the content of the RawFields.
// An empty RawFields may be passed to clear the fields.
//
// SetUnknown is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_EventPoolUpdated) SetUnknown(fields protoreflect.RawFields) {
	x.unknownFields = fields
}

// IsValid reports whether the message is valid.
//
// An invalid message is an empty, read-only value.
//
// An invalid message often corresponds to a nil pointer of the concrete
// message type, but the details are implementation dependent.
// Validity is not part of the protobuf data model, and may not
// be preserved in marshaling or other operations.
func (x *fastReflection_EventPoolUpdated) IsValid() bool {
	return x != nil
}

// ProtoMethods returns optional fastReflectionFeature-path implementations of various operations.
// This method may return nil.
//
// The returned methods type is identical to
// "google.golang.org/protobuf/runtime/protoiface".Methods.
// Consult the protoiface package documentation for details.
func (x *fastReflection_EventPoolUpdated) ProtoMethods() *protoiface.Methods {
	size := func(input protoiface.SizeInput) protoiface.SizeOutput {
		x := input.Message.Interface().(*EventPoolUpdated)
		if x == nil {
			return protoiface.SizeOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Size:              0,
			}
		}
		options := runtime.SizeInputToOptions(input)
		_ = options
		var n int
		var l int
		_ = l
		l = len(x.OldBasePoolDenom)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.OldBasePoolAmount)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.NewBasePoolDenom)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.NewBasePoolAmount)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.OldArkPoolDelta)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.NewArkPoolDelta)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		if x.unknownFields != nil {
			n += len(x.unknownFields)
		}
		return protoiface.SizeOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Size:              n,
		}
	}

	marshal := func(input protoiface.MarshalInput) (protoiface.MarshalOutput, error) {
		x := input.Message.Interface().(*EventPoolUpdated)
		if x == nil {
			return protoiface.MarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Buf:               input.Buf,
			}, nil
		}
		options := runtime.MarshalInputToOptions(input)
		_ = options
		size := options.Size(x)
		dAtA := make([]byte, size)
		i := len(dAtA)
		_ = i
		var l int
		_ = l
		if x.unknownFields != nil {
			i -= len(x.unknownFields)
			copy(dAtA[i:], x.unknownFields)
		}
		if len(x.NewArkPoolDelta) > 0 {
			i -= len(x.NewArkPoolDelta)
			copy(dAtA[i:], x.NewArkPoolDelta)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.NewArkPoolDelta)))
			i--
			dAtA[i] = 0x32
		}
		if len(x.OldArkPoolDelta) > 0 {
			i -= len(x.OldArkPoolDelta)
			copy(dAtA[i:], x.OldArkPoolDelta)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.OldArkPoolDelta)))
			i--
			dAtA[i] = 0x2a
		}
		if len(x.NewBasePoolAmount) > 0 {
			i -= len(x.NewBasePoolAmount)
			copy(dAtA[i:], x.NewBasePoolAmount)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.NewBasePoolAmount)))
			i--
			dAtA[i] = 0x22
		}
		if len(x.NewBasePoolDenom) > 0 {
			i -= len(x.NewBasePoolDenom)
			copy(dAtA[i:], x.NewBasePoolDenom)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.NewBasePoolDenom)))
			i--
			dAtA[i] = 0x1a
		}
		if len(x.OldBasePoolAmount) > 0 {
			i -= len(x.OldBasePoolAmount)
			copy(dAtA[i:], x.OldBasePoolAmount)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.OldBasePoolAmount)))
			i--
			dAtA[i] = 0x12
		}
		if len(x.OldBasePoolDenom) > 0 {
			i -= len(x.OldBasePoolDenom)
			copy(dAtA[i:], x.OldBasePoolDenom)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.OldBasePoolDenom)))
			i--
			dAtA[i] = 0xa
		}
		if input.Buf != nil {
			input.Buf = append(input.Buf, dAtA...)
		} else {
			input.Buf = dAtA
		}
		return protoiface.MarshalOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Buf:               input.Buf,
		}, nil
	}
	unmarshal := func(input protoiface.UnmarshalInput) (protoiface.UnmarshalOutput, error) {
		x := input.Message.Interface().(*EventPoolUpdated)
		if x == nil {
			return protoiface.UnmarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Flags:             input.Flags,
			}, nil
		}
		options := runtime.UnmarshalInputToOptions(input)
		_ = options
		dAtA := input.Buf
		l := len(dAtA)
		iNdEx := 0
		for iNdEx < l {
			preIndex := iNdEx
			var wire uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
				}
				if iNdEx >= l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				wire |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			fieldNum := int32(wire >> 3)
			wireType := int(wire & 0x7)
			if wireType == 4 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: EventPoolUpdated: wiretype end group for non-group")
			}
			if fieldNum <= 0 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: EventPoolUpdated: illegal tag %d (wire type %d)", fieldNum, wire)
			}
			switch fieldNum {
			case 1:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field OldBasePoolDenom", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.OldBasePoolDenom = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 2:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field OldBasePoolAmount", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.OldBasePoolAmount = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 3:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field NewBasePoolDenom", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.NewBasePoolDenom = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 4:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field NewBasePoolAmount", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.NewBasePoolAmount = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 5:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field OldArkPoolDelta", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.OldArkPoolDelta = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 6:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field NewArkPoolDelta", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.NewArkPoolDelta = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			default:
				iNdEx = preIndex
				skippy, err := runtime.Skip(dAtA[iNdEx:])
				if err != nil {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, err
				}
				if (skippy < 0) || (iNdEx+skippy) < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if (iNdEx + skippy) > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				if !options.DiscardUnknown {
					x.unknownFields = append(x.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
				}
				iNdEx += skippy
			}
		}

		if iNdEx > l {
			return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
		}
		return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, nil
	}
	return &protoiface.Methods{
		NoUnkeyedLiterals: struct{}{},
		Flags:             protoiface.SupportMarshalDeterministic | protoiface.SupportUnmarshalDiscardUnknown,
		Size:              size,
		Marshal:           marshal,
		Unmarshal:         unmarshal,
		Merge:             nil,
		CheckInitialized:  nil,
	}
}

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.0
// 	protoc        (unknown)
// source: ark/market/v1/event.proto

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// EventSwap is emitted after a Market swap settles successfully.
type EventSwap struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Trader      string `protobuf:"bytes,1,opt,name=trader,proto3" json:"trader,omitempty"`
	Recipient   string `protobuf:"bytes,2,opt,name=recipient,proto3" json:"recipient,omitempty"`
	OfferDenom  string `protobuf:"bytes,3,opt,name=offer_denom,json=offerDenom,proto3" json:"offer_denom,omitempty"`
	OfferAmount string `protobuf:"bytes,4,opt,name=offer_amount,json=offerAmount,proto3" json:"offer_amount,omitempty"`
	SwapDenom   string `protobuf:"bytes,5,opt,name=swap_denom,json=swapDenom,proto3" json:"swap_denom,omitempty"`
	SwapAmount  string `protobuf:"bytes,6,opt,name=swap_amount,json=swapAmount,proto3" json:"swap_amount,omitempty"`
	FeeDenom    string `protobuf:"bytes,7,opt,name=fee_denom,json=feeDenom,proto3" json:"fee_denom,omitempty"`
	FeeAmount   string `protobuf:"bytes,8,opt,name=fee_amount,json=feeAmount,proto3" json:"fee_amount,omitempty"`
}

func (x *EventSwap) Reset() {
	*x = EventSwap{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ark_market_v1_event_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EventSwap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventSwap) ProtoMessage() {}

// Deprecated: Use EventSwap.ProtoReflect.Descriptor instead.
func (*EventSwap) Descriptor() ([]byte, []int) {
	return file_ark_market_v1_event_proto_rawDescGZIP(), []int{0}
}

func (x *EventSwap) GetTrader() string {
	if x != nil {
		return x.Trader
	}
	return ""
}

func (x *EventSwap) GetRecipient() string {
	if x != nil {
		return x.Recipient
	}
	return ""
}

func (x *EventSwap) GetOfferDenom() string {
	if x != nil {
		return x.OfferDenom
	}
	return ""
}

func (x *EventSwap) GetOfferAmount() string {
	if x != nil {
		return x.OfferAmount
	}
	return ""
}

func (x *EventSwap) GetSwapDenom() string {
	if x != nil {
		return x.SwapDenom
	}
	return ""
}

func (x *EventSwap) GetSwapAmount() string {
	if x != nil {
		return x.SwapAmount
	}
	return ""
}

func (x *EventSwap) GetFeeDenom() string {
	if x != nil {
		return x.FeeDenom
	}
	return ""
}

func (x *EventSwap) GetFeeAmount() string {
	if x != nil {
		return x.FeeAmount
	}
	return ""
}

// EventPoolUpdated is emitted after a Market virtual-pool update succeeds.
type EventPoolUpdated struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OldBasePoolDenom  string `protobuf:"bytes,1,opt,name=old_base_pool_denom,json=oldBasePoolDenom,proto3" json:"old_base_pool_denom,omitempty"`
	OldBasePoolAmount string `protobuf:"bytes,2,opt,name=old_base_pool_amount,json=oldBasePoolAmount,proto3" json:"old_base_pool_amount,omitempty"`
	NewBasePoolDenom  string `protobuf:"bytes,3,opt,name=new_base_pool_denom,json=newBasePoolDenom,proto3" json:"new_base_pool_denom,omitempty"`
	NewBasePoolAmount string `protobuf:"bytes,4,opt,name=new_base_pool_amount,json=newBasePoolAmount,proto3" json:"new_base_pool_amount,omitempty"`
	OldArkPoolDelta   string `protobuf:"bytes,5,opt,name=old_ark_pool_delta,json=oldArkPoolDelta,proto3" json:"old_ark_pool_delta,omitempty"`
	NewArkPoolDelta   string `protobuf:"bytes,6,opt,name=new_ark_pool_delta,json=newArkPoolDelta,proto3" json:"new_ark_pool_delta,omitempty"`
}

func (x *EventPoolUpdated) Reset() {
	*x = EventPoolUpdated{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ark_market_v1_event_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EventPoolUpdated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventPoolUpdated) ProtoMessage() {}

// Deprecated: Use EventPoolUpdated.ProtoReflect.Descriptor instead.
func (*EventPoolUpdated) Descriptor() ([]byte, []int) {
	return file_ark_market_v1_event_proto_rawDescGZIP(), []int{1}
}

func (x *EventPoolUpdated) GetOldBasePoolDenom() string {
	if x != nil {
		return x.OldBasePoolDenom
	}
	return ""
}

func (x *EventPoolUpdated) GetOldBasePoolAmount() string {
	if x != nil {
		return x.OldBasePoolAmount
	}
	return ""
}

func (x *EventPoolUpdated) GetNewBasePoolDenom() string {
	if x != nil {
		return x.NewBasePoolDenom
	}
	return ""
}

func (x *EventPoolUpdated) GetNewBasePoolAmount() string {
	if x != nil {
		return x.NewBasePoolAmount
	}
	return ""
}

func (x *EventPoolUpdated) GetOldArkPoolDelta() string {
	if x != nil {
		return x.OldArkPoolDelta
	}
	return ""
}

func (x *EventPoolUpdated) GetNewArkPoolDelta() string {
	if x != nil {
		return x.NewArkPoolDelta
	}
	return ""
}

var File_ark_market_v1_event_proto protoreflect.FileDescriptor

var file_ark_market_v1_event_proto_rawDesc = []byte{
	0x0a, 0x19, 0x61, 0x72, 0x6b, 0x2f, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x2f, 0x76, 0x31, 0x2f,
	0x65, 0x76, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x61, 0x72, 0x6b,
	0x2e, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x2e, 0x76, 0x31, 0x1a, 0x11, 0x61, 0x6d, 0x69, 0x6e,
	0x6f, 0x2f, 0x61, 0x6d, 0x69, 0x6e, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x19, 0x63,
	0x6f, 0x73, 0x6d, 0x6f, 0x73, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x6f, 0x73, 0x6d,
	0x6f, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x14, 0x67, 0x6f, 0x67, 0x6f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2f, 0x67, 0x6f, 0x67, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xd1,
	0x03, 0x0a, 0x09, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x53, 0x77, 0x61, 0x70, 0x12, 0x30, 0x0a, 0x06,
	0x74, 0x72, 0x61, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x42, 0x18, 0xd2, 0xb4,
	0x2d, 0x14, 0x63, 0x6f, 0x73, 0x6d, 0x6f, 0x73, 0x2e, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73,
	0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x52, 0x06, 0x74, 0x72, 0x61, 0x64, 0x65, 0x72, 0x12, 0x36,
	0x0a, 0x09, 0x72, 0x65, 0x63, 0x69, 0x70, 0x69, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x42, 0x18, 0xd2, 0xb4, 0x2d, 0x14, 0x63, 0x6f, 0x73, 0x6d, 0x6f, 0x73, 0x2e, 0x41, 0x64,
	0x64, 0x72, 0x65, 0x73, 0x73, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x52, 0x09, 0x72, 0x65, 0x63,
	0x69, 0x70, 0x69, 0x65, 0x6e, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x6f, 0x66, 0x66, 0x65, 0x72, 0x5f,
	0x64, 0x65, 0x6e, 0x6f, 0x6d, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6f, 0x66, 0x66,
	0x65, 0x72, 0x44, 0x65, 0x6e, 0x6f, 0x6d, 0x12, 0x53, 0x0a, 0x0c, 0x6f, 0x66, 0x66, 0x65, 0x72,
	0x5f, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x42, 0x30, 0xc8,
	0xde, 0x1f, 0x00, 0xda, 0xde, 0x1f, 0x15, 0x63, 0x6f, 0x73, 0x6d, 0x6f, 0x73, 0x73, 0x64, 0x6b,
	0x2e, 0x69, 0x6f, 0x2f, 0x6d, 0x61, 0x74, 0x68, 0x2e, 0x49, 0x6e, 0x74, 0xd2, 0xb4, 0x2d, 0x0a,
	0x63, 0x6f, 0x73, 0x6d, 0x6f, 0x73, 0x2e, 0x49, 0x6e, 0x74, 0xa8, 0xe7, 0xb0, 0x2a, 0x01, 0x52,
	0x0b, 0x6f, 0x66, 0x66, 0x65, 0x72, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1d, 0x0a, 0x0a,
	0x73, 0x77, 0x61, 0x70, 0x5f, 0x64, 0x65, 0x6e, 0x6f, 0x6d, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x73, 0x77, 0x61, 0x70, 0x44, 0x65, 0x6e, 0x6f, 0x6d, 0x12, 0x51, 0x0a, 0x0b, 0x73,
	0x77, 0x61, 0x70, 0x5f, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09,
	0x42, 0x30, 0xc8, 0xde, 0x1f, 0x00, 0xda, 0xde, 0x1f, 0x15, 0x63, 0x6f, 0x73, 0x6d, 0x6f, 0x73,
	0x73, 0x64, 0x6b, 0x2e, 0x69, 0x6f, 0x2f, 0x6d, 0x61, 0x74, 0x68, 0x2e, 0x49, 0x6e, 0x74, 0xd2,
	0xb4, 0x2d, 0x0a, 0x63, 0x6f, 0x73, 0x6d, 0x6f, 0x73, 0x2e, 0x49, 0x6e, 0x74, 0xa8, 0xe7, 0xb0,
	0x2a, 0x01, 0x52, 0x0a, 0x73, 0x77, 0x61, 0x70, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1b,
	0x0a, 0x09, 0x66, 0x65, 0x65, 0x5f, 0x64, 0x65, 0x6e, 0x6f, 0x6d, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x66, 0x65, 0x65, 0x44, 0x65, 0x6e, 0x6f, 0x6d, 0x12, 0x55, 0x0a, 0x0a, 0x66,
	0x65, 0x65, 0x5f, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x42,
	0x36, 0xc8, 0xde, 0x1f, 0x00, 0xda, 0xde, 0x1f, 0x1b, 0x63, 0x6f, 0x73, 0x6d, 0x6f, 0x73, 0x73,
	0x64, 0x6b, 0x2e, 0x69, 0x6f, 0x2f, 0x6d, 0x61, 0x74, 0x68, 0x2e, 0x4c, 0x65, 0x67, 0x61, 0x63,
	0x79, 0x44, 0x65, 0x63, 0xd2, 0xb4, 0x2d, 0x0a, 0x63, 0x6f, 0x73, 0x6d, 0x6f, 0x73, 0x2e, 0x44,
	0x65, 0x63, 0xa8, 0xe7, 0xb0, 0x2a, 0x01, 0x52, 0x09, 0x66, 0x65, 0x65, 0x41, 0x6d, 0x6f, 0x75,
	0x6e, 0x74, 0x22, 0x8c, 0x04, 0x0a, 0x10, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x50, 0x6f, 0x6f, 0x6c,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x12, 0x2d, 0x0a, 0x13, 0x6f, 0x6c, 0x64, 0x5f, 0x62,
	0x61, 0x73, 0x65, 0x5f, 0x70, 0x6f, 0x6f, 0x6c, 0x5f, 0x64, 0x65, 0x6e, 0x6f, 0x6d, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x6f, 0x6c, 0x64, 0x42, 0x61, 0x73, 0x65, 0x50, 0x6f, 0x6f,
	0x6c, 0x44, 0x65, 0x6e, 0x6f, 0x6d, 0x12, 0x67, 0x0a, 0x14, 0x6f, 0x6c, 0x64, 0x5f, 0x62, 0x61,
	0x73, 0x65, 0x5f, 0x70, 0x6f, 0x6f, 0x6c, 0x5f, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x42, 0x36, 0xc8, 0xde, 0x1f, 0x00, 0xda, 0xde, 0x1f, 0x1b, 0x63, 0x6f,
	0x73, 0x6d, 0x6f, 0x73, 0x73, 0x64, 0x6b, 0x2e, 0x69, 0x6f, 0x2f, 0x6d, 0x61, 0x74, 0x68, 0x2e,
	0x4c, 0x65, 0x67, 0x61, 0x63, 0x79, 0x44, 0x65, 0x63, 0xd2, 0xb4, 0x2d, 0x0a, 0x63, 0x6f, 0x73,
	0x6d, 0x6f, 0x73, 0x2e, 0x44, 0x65, 0x63, 0xa8, 0xe7, 0xb0, 0x2a, 0x01, 0x52, 0x11, 0x6f, 0x6c,
	0x64, 0x42, 0x61, 0x73, 0x65, 0x50, 0x6f, 0x6f, 0x6c, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12,
	0x2d, 0x0a, 0x13, 0x6e, 0x65, 0x77, 0x5f, 0x62, 0x61, 0x73, 0x65, 0x5f, 0x70, 0x6f, 0x6f, 0x6c,
	0x5f, 0x64, 0x65, 0x6e, 0x6f, 0x6d, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x6e, 0x65,
	0x77, 0x42, 0x61, 0x73, 0x65, 0x50, 0x6f, 0x6f, 0x6c, 0x44, 0x65, 0x6e, 0x6f, 0x6d, 0x12, 0x67,
	0x0a, 0x14, 0x6e, 0x65, 0x77, 0x5f, 0x62, 0x61, 0x73, 0x65, 0x5f, 0x70, 0x6f, 0x6f, 0x6c, 0x5f,
	0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x42, 0x36, 0xc8, 0xde,
	0x1f, 0x00, 0xda, 0xde, 0x1f, 0x1b, 0x63, 0x6f, 0x73, 0x6d, 0x6f, 0x73, 0x73, 0x64, 0x6b, 0x2e,
	0x69, 0x6f, 0x2f, 0x6d, 0x61, 0x74, 0x68, 0x2e, 0x4c, 0x65, 0x67, 0x61, 0x63, 0x79, 0x44, 0x65,
	0x63, 0xd2, 0xb4, 0x2d, 0x0a, 0x63, 0x6f, 0x73, 0x6d, 0x6f, 0x73, 0x2e, 0x44, 0x65, 0x63, 0xa8,
	0xe7, 0xb0, 0x2a, 0x01, 0x52, 0x11, 0x6e, 0x65, 0x77, 0x42, 0x61, 0x73, 0x65, 0x50, 0x6f, 0x6f,
	0x6c, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x63, 0x0a, 0x12, 0x6f, 0x6c, 0x64, 0x5f, 0x61,
	0x72, 0x6b, 0x5f, 0x70, 0x6f, 0x6f, 0x6c, 0x5f, 0x64, 0x65, 0x6c, 0x74, 0x61, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x09, 0x42, 0x36, 0xc8, 0xde, 0x1f, 0x00, 0xda, 0xde, 0x1f, 0x1b, 0x63, 0x6f, 0x73,
	0x6d, 0x6f, 0x73, 0x73, 0x64, 0x6b, 0x2e, 0x69, 0x6f, 0x2f, 0x6d, 0x61, 0x74, 0x68, 0x2e, 0x4c,
	0x65, 0x67, 0x61, 0x63, 0x79, 0x44, 0x65, 0x63, 0xd2, 0xb4, 0x2d, 0x0a, 0x63, 0x6f, 0x73, 0x6d,
	0x6f, 0x73, 0x2e, 0x44, 0x65, 0x63, 0xa8, 0xe7, 0xb0, 0x2a, 0x01, 0x52, 0x0f, 0x6f, 0x6c, 0x64,
	0x41, 0x72, 0x6b, 0x50, 0x6f, 0x6f, 0x6c, 0x44, 0x65, 0x6c, 0x74, 0x61, 0x12, 0x63, 0x0a, 0x12,
	0x6e, 0x65, 0x77, 0x5f, 0x61, 0x72, 0x6b, 0x5f, 0x70, 0x6f, 0x6f, 0x6c, 0x5f, 0x64, 0x65, 0x6c,
	0x74, 0x61, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x42, 0x36, 0xc8, 0xde, 0x1f, 0x00, 0xda, 0xde,
	0x1f, 0x1b, 0x63, 0x6f, 0x73, 0x6d, 0x6f, 0x73, 0x73, 0x64, 0x6b, 0x2e, 0x69, 0x6f, 0x2f, 0x6d,
	0x61, 0x74, 0x68, 0x2e, 0x4c, 0x65, 0x67, 0x61, 0x63, 0x79, 0x44, 0x65, 0x63, 0xd2, 0xb4, 0x2d,
	0x0a, 0x63, 0x6f, 0x73, 0x6d, 0x6f, 0x73, 0x2e, 0x44, 0x65, 0x63, 0xa8, 0xe7, 0xb0, 0x2a, 0x01,
	0x52, 0x0f, 0x6e, 0x65, 0x77, 0x41, 0x72, 0x6b, 0x50, 0x6f, 0x6f, 0x6c, 0x44, 0x65, 0x6c, 0x74,
	0x61, 0x42, 0x95, 0x01, 0x0a, 0x11, 0x63, 0x6f, 0x6d, 0x2e, 0x61, 0x72, 0x6b, 0x2e, 0x6d, 0x61,
	0x72, 0x6b, 0x65, 0x74, 0x2e, 0x76, 0x31, 0x42, 0x0a, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x50, 0x72,
	0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x1e, 0x61, 0x72, 0x6b, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61,
	0x72, 0x6b, 0x2f, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x2f, 0x76, 0x31, 0x3b, 0x6d, 0x61, 0x72,
	0x6b, 0x65, 0x74, 0x76, 0x31, 0xa2, 0x02, 0x03, 0x41, 0x4d, 0x58, 0xaa, 0x02, 0x0d, 0x41, 0x72,
	0x6b, 0x2e, 0x4d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x2e, 0x56, 0x31, 0xca, 0x02, 0x0d, 0x41, 0x72,
	0x6b, 0x5c, 0x4d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x5c, 0x56, 0x31, 0xe2, 0x02, 0x19, 0x41, 0x72,
	0x6b, 0x5c, 0x4d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x5c, 0x56, 0x31, 0x5c, 0x47, 0x50, 0x42, 0x4d,
	0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0xea, 0x02, 0x0f, 0x41, 0x72, 0x6b, 0x3a, 0x3a, 0x4d,
	0x61, 0x72, 0x6b, 0x65, 0x74, 0x3a, 0x3a, 0x56, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_ark_market_v1_event_proto_rawDescOnce sync.Once
	file_ark_market_v1_event_proto_rawDescData = file_ark_market_v1_event_proto_rawDesc
)

func file_ark_market_v1_event_proto_rawDescGZIP() []byte {
	file_ark_market_v1_event_proto_rawDescOnce.Do(func() {
		file_ark_market_v1_event_proto_rawDescData = protoimpl.X.CompressGZIP(file_ark_market_v1_event_proto_rawDescData)
	})
	return file_ark_market_v1_event_proto_rawDescData
}

var file_ark_market_v1_event_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_ark_market_v1_event_proto_goTypes = []interface{}{
	(*EventSwap)(nil),        // 0: ark.market.v1.EventSwap
	(*EventPoolUpdated)(nil), // 1: ark.market.v1.EventPoolUpdated
}
var file_ark_market_v1_event_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ark_market_v1_event_proto_init() }
func file_ark_market_v1_event_proto_init() {
	if File_ark_market_v1_event_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_ark_market_v1_event_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EventSwap); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ark_market_v1_event_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EventPoolUpdated); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ark_market_v1_event_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ark_market_v1_event_proto_goTypes,
		DependencyIndexes: file_ark_market_v1_event_proto_depIdxs,
		MessageInfos:      file_ark_market_v1_event_proto_msgTypes,
	}.Build()
	File_ark_market_v1_event_proto = out.File
	file_ark_market_v1_event_proto_rawDesc = nil
	file_ark_market_v1_event_proto_goTypes = nil
	file_ark_market_v1_event_proto_depIdxs = nil
}
