syntax = "proto3";
package ark.oracle.v1;

import "amino/amino.proto";
import "cosmos_proto/cosmos.proto";
import "gogoproto/gogo.proto";
import "google/protobuf/timestamp.proto";
import "ark/oracle/v1/oracle.proto";

option go_package = "ark/x/oracle/types";

// GenesisState defines the oracle module's genesis state.
message GenesisState {
  Params params = 1
      [ (gogoproto.nullable) = false, (amino.dont_omitempty) = true ];
  repeated ExchangeRate exchange_rates = 2 [
    (gogoproto.castrepeated) = "ExchangeRates",
    (gogoproto.nullable) = false,
    (amino.dont_omitempty) = true
  ];
  repeated ScoreWeight score_weights = 3
      [ (gogoproto.nullable) = false, (amino.dont_omitempty) = true ];
  repeated MissCount miss_counts = 4
      [ (gogoproto.nullable) = false, (amino.dont_omitempty) = true ];
  repeated TobinTax tobin_taxes = 5
      [ (gogoproto.nullable) = false, (amino.dont_omitempty) = true ];
}

// ExchangeRate - struct to store interpreted exchange rates data to store
message ExchangeRate {
  string denom = 1;
  string rate = 2 [
    (cosmos_proto.scalar) = "cosmos.Dec",
    (gogoproto.customtype) = "cosmossdk.io/math.LegacyDec",
    (gogoproto.nullable) = false,
    (amino.dont_omitempty) = true
  ];
  // BlockTimestamp tracks the block height associated with this price update.
  // We include block timestamp alongside the price to ensure that smart
  // contracts and applications are not utilizing stale oracle prices
  google.protobuf.Timestamp block_timestamp = 3
      [ (gogoproto.nullable) = false, (gogoproto.stdtime) = true ];

  // BlockHeight is height of block mentioned above
  uint64 block_height = 4;
}

// ScoreWeight defines a score weight and validator address pair used in
// oracle module's genesis state
message ScoreWeight {
  string validator_address = 1
      [ (cosmos_proto.scalar) = "cosmos.ValidatorAddressString" ];
  uint64 score_weight = 2;
}

// MissCount defines a miss count and validator address pair used in
// oracle module's genesis state
message MissCount {
  string validator_address = 1
      [ (cosmos_proto.scalar) = "cosmos.ValidatorAddressString" ];
  uint64 miss_count = 2;
}
