// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: ark/oracle/v1/event.proto

package types

import (
	cosmossdk_io_math "cosmossdk.io/math"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// EventExchangeRateUpdate is emitted after an Oracle exchange rate is stored.
type EventExchangeRateUpdate struct {
	Denom        string                      `protobuf:"bytes,1,opt,name=denom,proto3" json:"denom,omitempty"`
	ExchangeRate cosmossdk_io_math.LegacyDec `protobuf:"bytes,2,opt,name=exchange_rate,json=exchangeRate,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"exchange_rate"`
}

func (m *EventExchangeRateUpdate) Reset()         { *m = EventExchangeRateUpdate{} }
func (m *EventExchangeRateUpdate) String() string { return proto.CompactTextString(m) }
func (*EventExchangeRateUpdate) ProtoMessage()    {}
func (*EventExchangeRateUpdate) Descriptor() ([]byte, []int) {
	return fileDescriptor_df98b89084f88b97, []int{0}
}
func (m *EventExchangeRateUpdate) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EventExchangeRateUpdate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EventExchangeRateUpdate.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EventExchangeRateUpdate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventExchangeRateUpdate.Merge(m, src)
}
func (m *EventExchangeRateUpdate) XXX_Size() int {
	return m.Size()
}
func (m *EventExchangeRateUpdate) XXX_DiscardUnknown() {
	xxx_messageInfo_EventExchangeRateUpdate.DiscardUnknown(m)
}

var xxx_messageInfo_EventExchangeRateUpdate proto.InternalMessageInfo

func (m *EventExchangeRateUpdate) GetDenom() string {
	if m != nil {
		return m.Denom
	}
	return ""
}

// EventOracleJail is emitted after a validator is jailed for insufficient
// oracle attendance over one attendance window.
type EventOracleJail struct {
	Validator        string `protobuf:"bytes,1,opt,name=validator,proto3" json:"validator,omitempty"`
	EligibleBlocks   uint64 `protobuf:"varint,2,opt,name=eligible_blocks,json=eligibleBlocks,proto3" json:"eligible_blocks,omitempty"`
	AttendedBlocks   uint64 `protobuf:"varint,3,opt,name=attended_blocks,json=attendedBlocks,proto3" json:"attended_blocks,omitempty"`
	AttendanceWindow uint64 `protobuf:"varint,4,opt,name=attendance_window,json=attendanceWindow,proto3" json:"attendance_window,omitempty"`
}

func (m *EventOracleJail) Reset()         { *m = EventOracleJail{} }
func (m *EventOracleJail) String() string { return proto.CompactTextString(m) }
func (*EventOracleJail) ProtoMessage()    {}
func (*EventOracleJail) Descriptor() ([]byte, []int) {
	return fileDescriptor_df98b89084f88b97, []int{1}
}
func (m *EventOracleJail) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EventOracleJail) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EventOracleJail.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EventOracleJail) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventOracleJail.Merge(m, src)
}
func (m *EventOracleJail) XXX_Size() int {
	return m.Size()
}
func (m *EventOracleJail) XXX_DiscardUnknown() {
	xxx_messageInfo_EventOracleJail.DiscardUnknown(m)
}

var xxx_messageInfo_EventOracleJail proto.InternalMessageInfo

func (m *EventOracleJail) GetValidator() string {
	if m != nil {
		return m.Validator
	}
	return ""
}

func (m *EventOracleJail) GetEligibleBlocks() uint64 {
	if m != nil {
		return m.EligibleBlocks
	}
	return 0
}

func (m *EventOracleJail) GetAttendedBlocks() uint64 {
	if m != nil {
		return m.AttendedBlocks
	}
	return 0
}

func (m *EventOracleJail) GetAttendanceWindow() uint64 {
	if m != nil {
		return m.AttendanceWindow
	}
	return 0
}

// EventFeedTransitionScheduled is emitted when one feed transition is
// scheduled.
type EventFeedTransitionScheduled struct {
	Denom                string        `protobuf:"bytes,1,opt,name=denom,proto3" json:"denom,omitempty"`
	Direction            FeedDirection `protobuf:"varint,2,opt,name=direction,proto3,enum=ark.oracle.v1.FeedDirection" json:"direction,omitempty"`
	ActivationVoteHeight int64         `protobuf:"varint,3,opt,name=activation_vote_height,json=activationVoteHeight,proto3" json:"activation_vote_height,omitempty"`
	ResultingVersion     uint64        `protobuf:"varint,4,opt,name=resulting_version,json=resultingVersion,proto3" json:"resulting_version,omitempty"`
}

func (m *EventFeedTransitionScheduled) Reset()         { *m = EventFeedTransitionScheduled{} }
func (m *EventFeedTransitionScheduled) String() string { return proto.CompactTextString(m) }
func (*EventFeedTransitionScheduled) ProtoMessage()    {}
func (*EventFeedTransitionScheduled) Descriptor() ([]byte, []int) {
	return fileDescriptor_df98b89084f88b97, []int{2}
}
func (m *EventFeedTransitionScheduled) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EventFeedTransitionScheduled) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EventFeedTransitionScheduled.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EventFeedTransitionScheduled) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventFeedTransitionScheduled.Merge(m, src)
}
func (m *EventFeedTransitionScheduled) XXX_Size() int {
	return m.Size()
}
func (m *EventFeedTransitionScheduled) XXX_DiscardUnknown() {
	xxx_messageInfo_EventFeedTransitionScheduled.DiscardUnknown(m)
}

var xxx_messageInfo_EventFeedTransitionScheduled proto.InternalMessageInfo

func (m *EventFeedTransitionScheduled) GetDenom() string {
	if m != nil {
		return m.Denom
	}
	return ""
}

func (m *EventFeedTransitionScheduled) GetDirection() FeedDirection {
	if m != nil {
		return m.Direction
	}
	return FeedDirection_FEED_DIRECTION_UNSPECIFIED
}

func (m *EventFeedTransitionScheduled) GetActivationVoteHeight() int64 {
	if m != nil {
		return m.ActivationVoteHeight
	}
	return 0
}

func (m *EventFeedTransitionScheduled) GetResultingVersion() uint64 {
	if m != nil {
		return m.ResultingVersion
	}
	return 0
}

// EventFeedsActivated is emitted once per promoted activation batch.
type EventFeedsActivated struct {
	Version       uint64   `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	AddedDenoms   []string `protobuf:"bytes,2,rep,name=added_denoms,json=addedDenoms,proto3" json:"added_denoms,omitempty"`
	RemovedDenoms []string `protobuf:"bytes,3,rep,name=removed_denoms,json=removedDenoms,proto3" json:"removed_denoms,omitempty"`
}

func (m *EventFeedsActivated) Reset()         { *m = EventFeedsActivated{} }
func (m *EventFeedsActivated) String() string { return proto.CompactTextString(m) }
func (*EventFeedsActivated) ProtoMessage()    {}
func (*EventFeedsActivated) Descriptor() ([]byte, []int) {
	return fileDescriptor_df98b89084f88b97, []int{3}
}
func (m *EventFeedsActivated) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EventFeedsActivated) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EventFeedsActivated.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EventFeedsActivated) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventFeedsActivated.Merge(m, src)
}
func (m *EventFeedsActivated) XXX_Size() int {
	return m.Size()
}
func (m *EventFeedsActivated) XXX_DiscardUnknown() {
	xxx_messageInfo_EventFeedsActivated.DiscardUnknown(m)
}

var xxx_messageInfo_EventFeedsActivated proto.InternalMessageInfo

func (m *EventFeedsActivated) GetVersion() uint64 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *EventFeedsActivated) GetAddedDenoms() []string {
	if m != nil {
		return m.AddedDenoms
	}
	return nil
}

func (m *EventFeedsActivated) GetRemovedDenoms() []string {
	if m != nil {
		return m.RemovedDenoms
	}
	return nil
}

// EventReferenceDenomUpdated is emitted after every protocol reference denom
// write.
type EventReferenceDenomUpdated struct {
	ReferenceDenom string `protobuf:"bytes,1,opt,name=reference_denom,json=referenceDenom,proto3" json:"reference_denom,omitempty"`
}

func (m *EventReferenceDenomUpdated) Reset()         { *m = EventReferenceDenomUpdated{} }
func (m *EventReferenceDenomUpdated) String() string { return proto.CompactTextString(m) }
func (*EventReferenceDenomUpdated) ProtoMessage()    {}
func (*EventReferenceDenomUpdated) Descriptor() ([]byte, []int) {
	return fileDescriptor_df98b89084f88b97, []int{4}
}
func (m *EventReferenceDenomUpdated) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EventReferenceDenomUpdated) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EventReferenceDenomUpdated.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EventReferenceDenomUpdated) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventReferenceDenomUpdated.Merge(m, src)
}
func (m *EventReferenceDenomUpdated) XXX_Size() int {
	return m.Size()
}
func (m *EventReferenceDenomUpdated) XXX_DiscardUnknown() {
	xxx_messageInfo_EventReferenceDenomUpdated.DiscardUnknown(m)
}

var xxx_messageInfo_EventReferenceDenomUpdated proto.InternalMessageInfo

func (m *EventReferenceDenomUpdated) GetReferenceDenom() string {
	if m != nil {
		return m.ReferenceDenom
	}
	return ""
}

// EventOracleReward is emitted after a validator's Oracle rewards are funded.
type EventOracleReward struct {
	Validator string                                   `protobuf:"bytes,1,opt,name=validator,proto3" json:"validator,omitempty"`
	Rewards   github_com_cosmos_cosmos_sdk_types.Coins `protobuf:"bytes,2,rep,name=rewards,proto3,castrepeated=github.com/cosmos/cosmos-sdk/types.Coins" json:"rewards"`
}

func (m *EventOracleReward) Reset()         { *m = EventOracleReward{} }
func (m *EventOracleReward) String() string { return proto.CompactTextString(m) }
func (*EventOracleReward) ProtoMessage()    {}
func (*EventOracleReward) Descriptor() ([]byte, []int) {
	return fileDescriptor_df98b89084f88b97, []int{5}
}
func (m *EventOracleReward) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EventOracleReward) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EventOracleReward.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EventOracleReward) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventOracleReward.Merge(m, src)
}
func (m *EventOracleReward) XXX_Size() int {
	return m.Size()
}
func (m *EventOracleReward) XXX_DiscardUnknown() {
	xxx_messageInfo_EventOracleReward.DiscardUnknown(m)
}

var xxx_messageInfo_EventOracleReward proto.InternalMessageInfo

func (m *EventOracleReward) GetValidator() string {
	if m != nil {
		return m.Validator
	}
	return ""
}

func (m *EventOracleReward) GetRewards() github_com_cosmos_cosmos_sdk_types.Coins {
	if m != nil {
		return m.Rewards
	}
	return nil
}

func init() {
	proto.RegisterType((*EventExchangeRateUpdate)(nil), "ark.oracle.v1.EventExchangeRateUpdate")
	proto.RegisterType((*EventOracleJail)(nil), "ark.oracle.v1.EventOracleJail")
	proto.RegisterType((*EventFeedTransitionScheduled)(nil), "ark.oracle.v1.EventFeedTransitionScheduled")
	proto.RegisterType((*EventFeedsActivated)(nil), "ark.oracle.v1.EventFeedsActivated")
	proto.RegisterType((*EventReferenceDenomUpdated)(nil), "ark.oracle.v1.EventReferenceDenomUpdated")
	proto.RegisterType((*EventOracleReward)(nil), "ark.oracle.v1.EventOracleReward")
}

func init() { proto.RegisterFile("ark/oracle/v1/event.proto", fileDescriptor_df98b89084f88b97) }

var fileDescriptor_df98b89084f88b97 = []byte{
	// 670 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x54, 0x4f, 0x4f, 0x13, 0x41,
	0x1c, 0xed, 0x5a, 0x90, 0x74, 0x80, 0x22, 0x2b, 0x51, 0xa8, 0xd8, 0x4a, 0x13, 0x23, 0x31, 0xb2,
	0x1b, 0x30, 0x7a, 0xf1, 0x60, 0xa8, 0xc5, 0x18, 0x63, 0x62, 0xb2, 0x28, 0x26, 0x7a, 0xd8, 0x4c,
	0x77, 0x7e, 0x6e, 0xc7, 0x6e, 0x67, 0xc8, 0xcc, 0xb0, 0xc0, 0xcd, 0x0f, 0xe0, 0xc1, 0x8f, 0x61,
	0x3c, 0x79, 0xe0, 0x03, 0x78, 0xe4, 0x48, 0x38, 0x19, 0x0f, 0x68, 0x20, 0x51, 0x3f, 0x86, 0x99,
	0x3f, 0x4b, 0xdb, 0x83, 0x27, 0x2f, 0xed, 0xce, 0x7b, 0xef, 0xf7, 0x9b, 0xf7, 0xe6, 0x1f, 0x5a,
	0xc0, 0xa2, 0x17, 0x72, 0x81, 0x93, 0x0c, 0xc2, 0x7c, 0x35, 0x84, 0x1c, 0x98, 0x0a, 0xb6, 0x05,
	0x57, 0xdc, 0x9f, 0xc6, 0xa2, 0x17, 0x58, 0x2a, 0xc8, 0x57, 0x6b, 0xb3, 0xb8, 0x4f, 0x19, 0x0f,
	0xcd, 0xaf, 0x55, 0xd4, 0x6a, 0xa3, 0xc5, 0x4e, 0x6b, 0xb9, 0x7a, 0xc2, 0x65, 0x9f, 0xcb, 0xb0,
	0x83, 0xa5, 0x26, 0x3b, 0xa0, 0xf0, 0x6a, 0x98, 0x70, 0xca, 0x1c, 0xbf, 0x60, 0xf9, 0xd8, 0x8c,
	0x42, 0x3b, 0x70, 0xd4, 0x5c, 0xca, 0x53, 0x6e, 0x71, 0xfd, 0x65, 0xd1, 0xe6, 0x07, 0x0f, 0x5d,
	0xdd, 0xd0, 0xf6, 0x36, 0xf6, 0x92, 0x2e, 0x66, 0x29, 0x44, 0x58, 0xc1, 0xcb, 0x6d, 0x82, 0x15,
	0xf8, 0x73, 0x68, 0x9c, 0x00, 0xe3, 0xfd, 0x79, 0xef, 0x86, 0xb7, 0x5c, 0x89, 0xec, 0xc0, 0x7f,
	0x83, 0xa6, 0xc1, 0x69, 0x63, 0x81, 0x15, 0xcc, 0x5f, 0xd0, 0x6c, 0xeb, 0xfe, 0xe1, 0x49, 0xa3,
	0xf4, 0xfd, 0xa4, 0x71, 0xcd, 0x4e, 0x2a, 0x49, 0x2f, 0xa0, 0x3c, 0xec, 0x63, 0xd5, 0x0d, 0x9e,
	0x41, 0x8a, 0x93, 0xfd, 0x36, 0x24, 0xc7, 0x07, 0x2b, 0xc8, 0x79, 0x6a, 0x43, 0xf2, 0xe9, 0xf7,
	0x97, 0xdb, 0x5e, 0x34, 0x05, 0x43, 0x13, 0x37, 0x7f, 0x79, 0x68, 0xc6, 0xd8, 0x79, 0x6e, 0x52,
	0x3f, 0xc5, 0x34, 0xf3, 0x1f, 0xa2, 0x4a, 0x8e, 0x33, 0x4a, 0xb0, 0xe2, 0xc2, 0x5a, 0x69, 0x2d,
	0x1d, 0x1f, 0xac, 0x5c, 0x77, 0x9d, 0xb6, 0x0a, 0x6e, 0x9d, 0x10, 0x01, 0x52, 0x6e, 0x2a, 0x41,
	0x59, 0x1a, 0x0d, 0x6a, 0xfc, 0x00, 0xcd, 0x40, 0x46, 0x53, 0xda, 0xc9, 0x20, 0xee, 0x64, 0x3c,
	0xe9, 0x49, 0xe3, 0x79, 0xac, 0x35, 0x6e, 0x2d, 0x54, 0x0b, 0xb6, 0x65, 0x48, 0xad, 0xc7, 0x4a,
	0x01, 0x23, 0x40, 0x0a, 0x7d, 0x79, 0x44, 0x5f, 0xb0, 0x4e, 0xbf, 0x86, 0x66, 0x2d, 0x82, 0x59,
	0x02, 0xf1, 0x2e, 0x65, 0x84, 0xef, 0xce, 0x8f, 0x0d, 0x57, 0x5c, 0x1a, 0xf0, 0xaf, 0x0c, 0xdd,
	0xfc, 0xe3, 0xa1, 0x45, 0x13, 0xf4, 0x31, 0x00, 0x79, 0x21, 0x30, 0x93, 0x54, 0x51, 0xce, 0x36,
	0x93, 0x2e, 0x90, 0x9d, 0x0c, 0xc8, 0x3f, 0x16, 0x7f, 0x1d, 0x55, 0x08, 0x15, 0x90, 0x68, 0xad,
	0x09, 0x51, 0x5d, 0x5b, 0x0c, 0x46, 0x4e, 0x54, 0xa0, 0x1b, 0xb6, 0x0b, 0x4d, 0x61, 0x60, 0x50,
	0xe5, 0x3f, 0x40, 0x57, 0x70, 0xa2, 0x68, 0x8e, 0xf5, 0x28, 0xce, 0xb9, 0x82, 0xb8, 0x0b, 0x34,
	0xed, 0x2a, 0x13, 0xb2, 0x5c, 0x54, 0xcc, 0x0d, 0x44, 0x5b, 0x5c, 0xc1, 0x13, 0x23, 0xd1, 0x51,
	0x05, 0xc8, 0x9d, 0x4c, 0x51, 0x96, 0xc6, 0x39, 0x08, 0xa9, 0x7d, 0x8c, 0x46, 0x3d, 0xe7, 0xb7,
	0x2c, 0xdd, 0x7c, 0xef, 0xa1, 0xcb, 0xe7, 0x51, 0xe5, 0xba, 0x6d, 0x0b, 0xc4, 0x6f, 0xa0, 0x89,
	0xa2, 0x83, 0x37, 0xdc, 0xa1, 0x40, 0xfd, 0x25, 0x34, 0x85, 0x89, 0xde, 0x04, 0x93, 0x5d, 0x6f,
	0x5a, 0x79, 0xb9, 0x12, 0x4d, 0x1a, 0xac, 0x6d, 0x20, 0xff, 0x26, 0xaa, 0x0a, 0xe8, 0xf3, 0x7c,
	0x20, 0x2a, 0x1b, 0xd1, 0xb4, 0x43, 0xad, 0xac, 0xb9, 0x81, 0x6a, 0xc6, 0x41, 0x04, 0x6f, 0x41,
	0x00, 0x4b, 0xc0, 0xe0, 0xf6, 0x98, 0x13, 0xff, 0x16, 0x9a, 0x11, 0x05, 0x11, 0x0f, 0x2f, 0x7a,
	0x55, 0x8c, 0xe8, 0x9b, 0x5f, 0x3d, 0x34, 0x3b, 0x74, 0x3a, 0x23, 0xd8, 0xc5, 0x82, 0xfc, 0xff,
	0xf9, 0x7c, 0x87, 0x26, 0x84, 0x69, 0x65, 0x23, 0x4e, 0xae, 0x2d, 0x04, 0xae, 0x56, 0x5f, 0xf3,
	0xc0, 0x5d, 0xf3, 0xe0, 0x11, 0xa7, 0xac, 0x75, 0x4f, 0x5f, 0xb3, 0xcf, 0x3f, 0x1a, 0xcb, 0x29,
	0x55, 0xdd, 0x9d, 0x4e, 0x90, 0xf0, 0xbe, 0xbb, 0xe6, 0xee, 0x6f, 0x45, 0x92, 0x5e, 0xa8, 0xf6,
	0xb7, 0x41, 0x9a, 0x02, 0xe9, 0xd6, 0xd4, 0x4d, 0xd0, 0xba, 0x73, 0x78, 0x5a, 0xf7, 0x8e, 0x4e,
	0xeb, 0xde, 0xcf, 0xd3, 0xba, 0xf7, 0xf1, 0xac, 0x5e, 0x3a, 0x3a, 0xab, 0x97, 0xbe, 0x9d, 0xd5,
	0x4b, 0xaf, 0x7d, 0xfd, 0xec, 0xec, 0x15, 0x0f, 0x8f, 0xe9, 0xd0, 0xb9, 0x68, 0x1e, 0x89, 0xbb,
	0x7f, 0x03, 0x00, 0x00, 0xff, 0xff, 0x93, 0xff, 0xb0, 0xea, 0xd0, 0x04, 0x00, 0x00,
}

func (m *EventExchangeRateUpdate) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EventExchangeRateUpdate) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EventExchangeRateUpdate) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.ExchangeRate.Size()
		i -= size
		if _, err := m.ExchangeRate.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintEvent(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.Denom) > 0 {
		i -= len(m.Denom)
		copy(dAtA[i:], m.Denom)
		i = encodeVarintEvent(dAtA, i, uint64(len(m.Denom)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *EventOracleJail) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EventOracleJail) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EventOracleJail) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.AttendanceWindow != 0 {
		i = encodeVarintEvent(dAtA, i, uint64(m.AttendanceWindow))
		i--
		dAtA[i] = 0x20
	}
	if m.AttendedBlocks != 0 {
		i = encodeVarintEvent(dAtA, i, uint64(m.AttendedBlocks))
		i--
		dAtA[i] = 0x18
	}
	if m.EligibleBlocks != 0 {
		i = encodeVarintEvent(dAtA, i, uint64(m.EligibleBlocks))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Validator) > 0 {
		i -= len(m.Validator)
		copy(dAtA[i:], m.Validator)
		i = encodeVarintEvent(dAtA, i, uint64(len(m.Validator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *EventFeedTransitionScheduled) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EventFeedTransitionScheduled) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EventFeedTransitionScheduled) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.ResultingVersion != 0 {
		i = encodeVarintEvent(dAtA, i, uint64(m.ResultingVersion))
		i--
		dAtA[i] = 0x20
	}
	if m.ActivationVoteHeight != 0 {
		i = encodeVarintEvent(dAtA, i, uint64(m.ActivationVoteHeight))
		i--
		dAtA[i] = 0x18
	}
	if m.Direction != 0 {
		i = encodeVarintEvent(dAtA, i, uint64(m.Direction))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Denom) > 0 {
		i -= len(m.Denom)
		copy(dAtA[i:], m.Denom)
		i = encodeVarintEvent(dAtA, i, uint64(len(m.Denom)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *EventFeedsActivated) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EventFeedsActivated) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EventFeedsActivated) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.RemovedDenoms) > 0 {
		for iNdEx := len(m.RemovedDenoms) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.RemovedDenoms[iNdEx])
			copy(dAtA[i:], m.RemovedDenoms[iNdEx])
			i = encodeVarintEvent(dAtA, i, uint64(len(m.RemovedDenoms[iNdEx])))
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.AddedDenoms) > 0 {
		for iNdEx := len(m.AddedDenoms) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.AddedDenoms[iNdEx])
			copy(dAtA[i:], m.AddedDenoms[iNdEx])
			i = encodeVarintEvent(dAtA, i, uint64(len(m.AddedDenoms[iNdEx])))
			i--
			dAtA[i] = 0x12
		}
	}
	if m.Version != 0 {
		i = encodeVarintEvent(dAtA, i, uint64(m.Version))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *EventReferenceDenomUpdated) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EventReferenceDenomUpdated) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EventReferenceDenomUpdated) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ReferenceDenom) > 0 {
		i -= len(m.ReferenceDenom)
		copy(dAtA[i:], m.ReferenceDenom)
		i = encodeVarintEvent(dAtA, i, uint64(len(m.ReferenceDenom)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *EventOracleReward) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EventOracleReward) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EventOracleReward) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Rewards) > 0 {
		for iNdEx := len(m.Rewards) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Rewards[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintEvent(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.Validator) > 0 {
		i -= len(m.Validator)
		copy(dAtA[i:], m.Validator)
		i = encodeVarintEvent(dAtA, i, uint64(len(m.Validator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintEvent(dAtA []byte, offset int, v uint64) int {
	offset -= sovEvent(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *EventExchangeRateUpdate) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Denom)
	if l > 0 {
		n += 1 + l + sovEvent(uint64(l))
	}
	l = m.ExchangeRate.Size()
	n += 1 + l + sovEvent(uint64(l))
	return n
}

func (m *EventOracleJail) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Validator)
	if l > 0 {
		n += 1 + l + sovEvent(uint64(l))
	}
	if m.EligibleBlocks != 0 {
		n += 1 + sovEvent(uint64(m.EligibleBlocks))
	}
	if m.AttendedBlocks != 0 {
		n += 1 + sovEvent(uint64(m.AttendedBlocks))
	}
	if m.AttendanceWindow != 0 {
		n += 1 + sovEvent(uint64(m.AttendanceWindow))
	}
	return n
}

func (m *EventFeedTransitionScheduled) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Denom)
	if l > 0 {
		n += 1 + l + sovEvent(uint64(l))
	}
	if m.Direction != 0 {
		n += 1 + sovEvent(uint64(m.Direction))
	}
	if m.ActivationVoteHeight != 0 {
		n += 1 + sovEvent(uint64(m.ActivationVoteHeight))
	}
	if m.ResultingVersion != 0 {
		n += 1 + sovEvent(uint64(m.ResultingVersion))
	}
	return n
}

func (m *EventFeedsActivated) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Version != 0 {
		n += 1 + sovEvent(uint64(m.Version))
	}
	if len(m.AddedDenoms) > 0 {
		for _, s := range m.AddedDenoms {
			l = len(s)
			n += 1 + l + sovEvent(uint64(l))
		}
	}
	if len(m.RemovedDenoms) > 0 {
		for _, s := range m.RemovedDenoms {
			l = len(s)
			n += 1 + l + sovEvent(uint64(l))
		}
	}
	return n
}

func (m *EventReferenceDenomUpdated) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ReferenceDenom)
	if l > 0 {
		n += 1 + l + sovEvent(uint64(l))
	}
	return n
}

func (m *EventOracleReward) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Validator)
	if l > 0 {
		n += 1 + l + sovEvent(uint64(l))
	}
	if len(m.Rewards) > 0 {
		for _, e := range m.Rewards {
			l = e.Size()
			n += 1 + l + sovEvent(uint64(l))
		}
	}
	return n
}

func sovEvent(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozEvent(x uint64) (n int) {
	return sovEvent(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *EventExchangeRateUpdate) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEvent
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EventExchangeRateUpdate: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EventExchangeRateUpdate: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Denom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Denom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ExchangeRate", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ExchangeRate.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipEvent(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEvent
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *EventOracleJail) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEvent
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EventOracleJail: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EventOracleJail: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Validator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Validator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EligibleBlocks", wireType)
			}
			m.EligibleBlocks = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.EligibleBlocks |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AttendedBlocks", wireType)
			}
			m.AttendedBlocks = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AttendedBlocks |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AttendanceWindow", wireType)
			}
			m.AttendanceWindow = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AttendanceWindow |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipEvent(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEvent
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *EventFeedTransitionScheduled) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEvent
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EventFeedTransitionScheduled: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EventFeedTransitionScheduled: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Denom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Denom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Direction", wireType)
			}
			m.Direction = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Direction |= FeedDirection(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ActivationVoteHeight", wireType)
			}
			m.ActivationVoteHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ActivationVoteHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ResultingVersion", wireType)
			}
			m.ResultingVersion = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ResultingVersion |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipEvent(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEvent
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *EventFeedsActivated) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEvent
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EventFeedsActivated: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EventFeedsActivated: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Version", wireType)
			}
			m.Version = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Version |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AddedDenoms", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AddedDenoms = append(m.AddedDenoms, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RemovedDenoms", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RemovedDenoms = append(m.RemovedDenoms, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipEvent(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEvent
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *EventReferenceDenomUpdated) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEvent
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EventReferenceDenomUpdated: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EventReferenceDenomUpdated: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ReferenceDenom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ReferenceDenom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipEvent(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEvent
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *EventOracleReward) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEvent
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EventOracleReward: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EventOracleReward: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Validator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Validator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Rewards", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Rewards = append(m.Rewards, types.Coin{})
			if err := m.Rewards[len(m.Rewards)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipEvent(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEvent
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipEvent(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowEvent
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthEvent
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupEvent
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthEvent
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthEvent        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowEvent          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupEvent = fmt.Errorf("proto: unexpected end of group")
)
