syntax = "proto3";

package noah.oracle.module.v1;

import "cosmos/app/v1alpha1/module.proto";

// Module is the config object for the oracle module.
message Module {
  option (cosmos.app.v1alpha1.module) = {
    go_import : "noah/x/oracle"
  };

  // authority defines the custom module authority. If not set, defaults to the
  // governance module.
  string authority = 1;

  // distribution_name defines the module account name to
  // which the community pool remainder is sent. If not set, defaults to
  // "distribution".
  string distribution_name = 2;
}
