syntax = "proto3";
package ark.treasury.v1;

import "amino/amino.proto";
import "ark/treasury/v1/treasury.proto";
import "cosmos_proto/cosmos.proto";
import "gogoproto/gogo.proto";

option go_package = "ark/x/treasury/types";

// GenesisState defines the treasury module's genesis state.
message GenesisState {
  Params params = 1
      [ (gogoproto.nullable) = false, (amino.dont_omitempty) = true ];
  repeated TaxCap tax_caps = 2
      [ (gogoproto.nullable) = false, (amino.dont_omitempty) = true ];
  ClaimsMandate claims_mandate = 3
      [ (gogoproto.nullable) = false, (amino.dont_omitempty) = true ];
  string claims_allowance_used = 4 [
    (cosmos_proto.scalar) = "cosmos.Int",
    (gogoproto.customtype) = "cosmossdk.io/math.Int",
    (gogoproto.nullable) = false,
    (amino.dont_omitempty) = true
  ];
  string insurance_reserved = 5 [
    (cosmos_proto.scalar) = "cosmos.Int",
    (gogoproto.customtype) = "cosmossdk.io/math.Int",
    (gogoproto.nullable) = false,
    (amino.dont_omitempty) = true
  ];
  // next_claim_id is the next globally available Treasury claim identifier.
  uint64 next_claim_id = 6 [ (amino.dont_omitempty) = true ];
  repeated Claim claims = 7
      [ (gogoproto.nullable) = false, (amino.dont_omitempty) = true ];
  RewardFundingState reward_funding = 8
      [ (gogoproto.nullable) = false, (amino.dont_omitempty) = true ];
  MonetaryMandate monetary_mandate = 9
      [ (gogoproto.nullable) = false, (amino.dont_omitempty) = true ];
  MonetaryPolicy monetary_policy = 10
      [ (gogoproto.nullable) = false, (amino.dont_omitempty) = true ];
}
