syntax = "proto3";
package ark.transport.v1;

import "gogoproto/gogo.proto";
import "google/api/annotations.proto";
import "google/protobuf/timestamp.proto";

option go_package = "ark/oracle/types";

// Oracle defines the gRPC oracle service.
service Oracle {
  // Prices defines a method for fetching the latest prices.
  rpc Prices(OraclePricesRequest) returns (OraclePricesResponse) {
    option (google.api.http) = {
      get : "/ark/transport/v1/prices"
    };
  }

  // Version defines a method for fetching the current version of the oracle
  // service.
  rpc Version(OracleVersionRequest) returns (OracleVersionResponse) {
    option (google.api.http) = {
      get : "/ark/transport/v1/version"
    };
  }
}

// QueryPricesRequest defines the request type for the the Prices method.
message OraclePricesRequest {}

// QueryPricesResponse defines the response type for the Prices method.
message OraclePricesResponse {
  // Prices defines the list of prices.
  map<string, bytes> prices = 1 [ (gogoproto.nullable) = false ];

  // Timestamp defines the timestamp of the prices.
  google.protobuf.Timestamp timestamp = 2
      [ (gogoproto.nullable) = false, (gogoproto.stdtime) = true ];

  // Version defines the version of the oracle service that provided the prices.
  string version = 3;
}

// QueryVersionRequest defines the request type for the Version method.
message OracleVersionRequest {}

// QueryVersionResponse defines the response type for the Version method.
message OracleVersionResponse {
  // Version defines the current version of the oracle service.
  string version = 1;
}
